# Task B – MFCD vs VCD (Self-contained)
This notebook clones the repo, installs dependencies, downloads COCO val2014, runs VCD and MFCD, then prints a comparison table.

In [1]:
import torch
print('Torch:', torch.__version__)
print('CUDA:', torch.cuda.is_available())
if torch.cuda.is_available():
    print('GPU:', torch.cuda.get_device_name(0))
    print('CUDA Version:', torch.version.cuda)

Torch: 2.10.0+cu128
CUDA: True
GPU: NVIDIA RTX PRO 6000 Blackwell Server Edition
CUDA Version: 12.8

In [2]:
import os
ROOT = '/content/VCD_project'
REPO_URL = 'https://github.com/maxheef/ECE209_Project1.git'
BRANCH = 'main'
COCO_VAL = '/content/datasets/coco/val2014'
MODEL_PATH = 'liuhaotian/llava-v1.5-7b'
MFCD_MODEL_PATH = 'llava-hf/llava-1.5-7b-hf'
SEED = 55

# MFCD parameters (from MFCD readme)
MFC_HIGH_ALPHA = 1.0
MFC_LOW_ALPHA = 1.0
MFC_BETA = 0.3
MFC_HIGH_PASS_CUTOFF = 0.1
MFC_LOW_PASS_CUTOFF = 0.9
MFC_FILTER_TYPE = 'gaussian'
print('ROOT=', ROOT)

ROOT= /content/VCD_project

In [3]:
%%bash
set -euo pipefail
cd /content
if [ -d /content/VCD_project/.git ]; then
  git -C /content/VCD_project fetch --depth 1 origin ${BRANCH:-main}
  git -C /content/VCD_project reset --hard FETCH_HEAD
else
  rm -rf /content/VCD_project
  git clone --depth 1 --branch ${BRANCH:-main} ${REPO_URL:-https://github.com/maxheef/ECE209_Project1.git} /content/VCD_project
fi

if [ ! -d /content/VCD_project/originalMFCD/mfcd ]; then
  echo 'Missing /content/VCD_project/originalMFCD/mfcd (check repo contents)'.
  find /content/VCD_project -maxdepth 3 -type d | sed -n '1,120p'
  exit 1
fi

Cloning into '/content/VCD_project'...

In [4]:
import os
import subprocess
import shutil
from pathlib import Path

def run_cmd(cmd):
    process = subprocess.Popen(cmd, shell=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True, env=os.environ.copy())
    for line in process.stdout:
        print(line, end='')
    process.wait()
    if process.returncode != 0:
        raise Exception(f"Command failed: {cmd}")

# --- Configuration ---
CONDA_PATH = '/usr/local/miniconda'
REQ_FILE = '/content/VCD_project/requirements.txt'

VCD_ENV = 'vcd310'
MFCD_ENV = 'mfcd310'
VCD_PY = f'{CONDA_PATH}/envs/{VCD_ENV}/bin/python'
VCD_PIP = f'{CONDA_PATH}/envs/{VCD_ENV}/bin/pip'
MFCD_PY = f'{CONDA_PATH}/envs/{MFCD_ENV}/bin/python'
MFCD_PIP = f'{CONDA_PATH}/envs/{MFCD_ENV}/bin/pip'

# 1) Setup Miniconda
if not os.path.exists(CONDA_PATH):
    run_cmd('wget -q https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O /tmp/miniconda.sh')
    run_cmd(f'bash /tmp/miniconda.sh -b -p {CONDA_PATH}')

conda_bin = f'{CONDA_PATH}/bin/conda'
os.environ['CONDA_PLUGINS_AUTO_ACCEPT_TOS'] = 'yes'
run_cmd(f"{conda_bin} tos accept --override-channels --channel https://repo.anaconda.com/pkgs/main")
run_cmd(f"{conda_bin} tos accept --override-channels --channel https://repo.anaconda.com/pkgs/r")

# 2) (Re)create envs
for env_name in [VCD_ENV, MFCD_ENV]:
    env_path = f'{CONDA_PATH}/envs/{env_name}'
    if os.path.exists(env_path):
        shutil.rmtree(env_path)
    print(f'Creating environment {env_name} (Python 3.10)...')
    run_cmd(f"{conda_bin} create -n {env_name} python=3.10 -y")

# 3) Install base requirements in both envs
if not os.path.exists(REQ_FILE):
    raise FileNotFoundError(f'Missing requirements: {REQ_FILE}')

run_cmd(f"{VCD_PIP} install --upgrade pip setuptools wheel")
run_cmd(f"{VCD_PIP} install --no-cache-dir -r {REQ_FILE}")

run_cmd(f"{MFCD_PIP} install --upgrade pip setuptools wheel")
run_cmd(f"{MFCD_PIP} install --no-cache-dir -r {REQ_FILE}")

# 4) Pin versions
# VCD needs older transformers + tokenizers to avoid LLaVA config conflicts
run_cmd(f"{VCD_PIP} install --no-cache-dir 'transformers==4.31.0' 'tokenizers==0.13.3' 'numpy<2'")

# MFCD needs newer tokenizers for its bundled transformers fork
run_cmd(f"{MFCD_PIP} install --no-cache-dir 'tokenizers==0.21.0' 'numpy<2'")

# 5) Record python paths
Path('/tmp/mytasks_python_bin.txt').write_text(VCD_PY)
Path('/tmp/mytasks_python_bin_mfcd.txt').write_text(MFCD_PY)
print('VCD env:', VCD_PY)
print('MFCD env:', MFCD_PY)

run_cmd(f"{VCD_PY} -c 'import torch; print(\"VCD Python\", __import__(\"sys\").version); print(\"CUDA\", torch.cuda.is_available())'")
run_cmd(f"{MFCD_PY} -c 'import torch; print(\"MFCD Python\", __import__(\"sys\").version); print(\"CUDA\", torch.cuda.is_available())'")

PREFIX=/usr/local/miniconda
Unpacking bootstrapper...
Unpacking payload...

Installing base environment...

Preparing transaction: ...working... done
Executing transaction: ...working... done
installation finished.
WARNING:
    You currently have a PYTHONPATH environment variable set. This may cause
    unexpected behavior when running the Python interpreter in Miniconda3.
    For best results, please verify that your PYTHONPATH only points to
    directories of packages that are compatible with the Python interpreter
    in Miniconda3: /usr/local/miniconda
accepted Terms of Service for https://repo.anaconda.com/pkgs/main
accepted Terms of Service for https://repo.anaconda.com/pkgs/r
Creating environment vcd310 (Python 3.10)...
Jupyter detected...
2 channel Terms of Service accepted
Retrieving notices: done
Channels:
 - defaults
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /usr/local/miniconda/envs/vcd310

  added / updated specs:
    - python=3.10


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ld_impl_linux-64-2.44      |       h9e0c5a2_3         725 KB
    libnsl-2.0.0               |       h5eee18b_0          31 KB
    packaging-25.0             |  py310h06a4308_1         164 KB
    python-3.10.20             |       h741d88c_0        24.1 MB
    setuptools-80.10.2         |  py310h06a4308_0         1.3 MB
    sqlite-3.51.2              |       h3e8d24a_0         1.2 MB
    tzdata-2026a               |       he532380_0         117 KB
    wheel-0.46.3               |  py310h06a4308_0          54 KB
    ------------------------------------------------------------
                                           Total:        27.7 MB

The following NEW packages will be INSTALLED:

  _libgcc_mutex      pkgs/main/linux-64::_libgcc_mutex-0.1-main
  _openmp_mutex      pkgs/main/linux-64::_openmp_mutex-5.1-1_gnu
  bzip2              pkgs/main/linux-64::bzip2-1.0.8-h5eee18b_6
  ca-certificates    pkgs/main/linux-64::ca-certificates-2025.12.2-h06a4308_0
  ld_impl_linux-64   pkgs/main/linux-64::ld_impl_linux-64-2.44-h9e0c5a2_3
  libexpat           pkgs/main/linux-64::libexpat-2.7.4-h7354ed3_0
  libffi             pkgs/main/linux-64::libffi-3.4.4-h6a678d5_1
  libgcc             pkgs/main/linux-64::libgcc-15.2.0-h69a1729_7
  libgcc-ng          pkgs/main/linux-64::libgcc-ng-15.2.0-h166f726_7
  libgomp            pkgs/main/linux-64::libgomp-15.2.0-h4751f2c_7
  libnsl             pkgs/main/linux-64::libnsl-2.0.0-h5eee18b_0
  libstdcxx          pkgs/main/linux-64::libstdcxx-15.2.0-h39759b7_7
  libstdcxx-ng       pkgs/main/linux-64::libstdcxx-ng-15.2.0-hc03a8fd_7
  libuuid            pkgs/main/linux-64::libuuid-1.41.5-h5eee18b_0
  libxcb             pkgs/main/linux-64::libxcb-1.17.0-h9b100fa_0
  libzlib            pkgs/main/linux-64::libzlib-1.3.1-hb25bd0a_0
  ncurses            pkgs/main/linux-64::ncurses-6.5-h7934f7d_0
  openssl            pkgs/main/linux-64::openssl-3.5.5-h1b28b03_0
  packaging          pkgs/main/linux-64::packaging-25.0-py310h06a4308_1
  pip                pkgs/main/noarch::pip-26.0.1-pyhc872135_0
  pthread-stubs      pkgs/main/linux-64::pthread-stubs-0.3-h0ce48e5_1
  python             pkgs/main/linux-64::python-3.10.20-h741d88c_0
  readline           pkgs/main/linux-64::readline-8.3-hc2a1206_0
  setuptools         pkgs/main/linux-64::setuptools-80.10.2-py310h06a4308_0
  sqlite             pkgs/main/linux-64::sqlite-3.51.2-h3e8d24a_0
  tk                 pkgs/main/linux-64::tk-8.6.15-h54e0aa7_0
  tzdata             pkgs/main/noarch::tzdata-2026a-he532380_0
  wheel              pkgs/main/linux-64::wheel-0.46.3-py310h06a4308_0
  xorg-libx11        pkgs/main/linux-64::xorg-libx11-1.8.12-h9b100fa_1
  xorg-libxau        pkgs/main/linux-64::xorg-libxau-1.0.12-h9b100fa_0
  xorg-libxdmcp      pkgs/main/linux-64::xorg-libxdmcp-1.1.5-h9b100fa_0
  xorg-xorgproto     pkgs/main/linux-64::xorg-xorgproto-2024.1-h5eee18b_1
  xz                 pkgs/main/linux-64::xz-5.8.2-h448239c_0
  zlib               pkgs/main/linux-64::zlib-1.3.1-hb25bd0a_0



Downloading and Extracting Packages: ...working...
python-3.10.20       | 24.1 MB   |            |   0%

setuptools-80.10.2   | 1.3 MB    |            |   0%


sqlite-3.51.2        | 1.2 MB    |            |   0%



ld_impl_linux-64-2.4 | 725 KB    |            |   0%




packaging-25.0       | 164 KB    |            |   0%





tzdata-2026a         | 117 KB    |            |   0%






wheel-0.46.3         | 54 KB     |            |   0%







libnsl-2.0.0         | 31 KB     |            |   0%



ld_impl_linux-64-2.4 | 725 KB    | 2          |   2%


sqlite-3.51.2        | 1.2 MB    | 1          |   1%
python-3.10.20       | 24.1 MB   |            |   0%

setuptools-80.10.2   | 1.3 MB    | 1          |   1%



ld_impl_linux-64-2.4 | 725 KB    | ########## | 100%




packaging-25.0       | 164 KB    | 9          |  10%


sqlite-3.51.2        | 1.2 MB    | ########## | 100%



ld_impl_linux-64-2.4 | 725 KB    | ########## | 100%


sqlite-3.51.2        | 1.2 MB    | ########## | 100%




packaging-25.0       | 164 KB    | ########## | 100%

setuptools-80.10.2   | 1.3 MB    | ########## | 100%




packaging-25.0       | 164 KB    | ########## | 100%





tzdata-2026a         | 117 KB    | #3         |  14%





tzdata-2026a         | 117 KB    | ########## | 100%
python-3.10.20       | 24.1 MB   | ##2        |  22%







libnsl-2.0.0         | 31 KB     | #####1     |  52%







libnsl-2.0.0         | 31 KB     | ########## | 100%






wheel-0.46.3         | 54 KB     | ##9        |  30%






wheel-0.46.3         | 54 KB     | ########## | 100%







libnsl-2.0.0         | 31 KB     | ########## | 100%






wheel-0.46.3         | 54 KB     | ########## | 100%
python-3.10.20       | 24.1 MB   | ########1  |  82%





tzdata-2026a         | 117 KB    | ########## | 100%





tzdata-2026a         | 117 KB    | ########## | 100%

setuptools-80.10.2   | 1.3 MB    | ########## | 100%

setuptools-80.10.2   | 1.3 MB    | ########## | 100%
python-3.10.20       | 24.1 MB   | ########## | 100%
python-3.10.20       | 24.1 MB   | ########## | 100%



































                                                      done
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate vcd310
#
# To deactivate an active environment, use
#
#     $ conda deactivate

Creating environment mfcd310 (Python 3.10)...
Jupyter detected...
2 channel Terms of Service accepted
Channels:
 - defaults
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /usr/local/miniconda/envs/mfcd310

  added / updated specs:
    - python=3.10


The following NEW packages will be INSTALLED:

  _libgcc_mutex      pkgs/main/linux-64::_libgcc_mutex-0.1-main
  _openmp_mutex      pkgs/main/linux-64::_openmp_mutex-5.1-1_gnu
  bzip2              pkgs/main/linux-64::bzip2-1.0.8-h5eee18b_6
  ca-certificates    pkgs/main/linux-64::ca-certificates-2025.12.2-h06a4308_0
  ld_impl_linux-64   pkgs/main/linux-64::ld_impl_linux-64-2.44-h9e0c5a2_3
  libexpat           pkgs/main/linux-64::libexpat-2.7.4-h7354ed3_0
  libffi             pkgs/main/linux-64::libffi-3.4.4-h6a678d5_1
  libgcc             pkgs/main/linux-64::libgcc-15.2.0-h69a1729_7
  libgcc-ng          pkgs/main/linux-64::libgcc-ng-15.2.0-h166f726_7
  libgomp            pkgs/main/linux-64::libgomp-15.2.0-h4751f2c_7
  libnsl             pkgs/main/linux-64::libnsl-2.0.0-h5eee18b_0
  libstdcxx          pkgs/main/linux-64::libstdcxx-15.2.0-h39759b7_7
  libstdcxx-ng       pkgs/main/linux-64::libstdcxx-ng-15.2.0-hc03a8fd_7
  libuuid            pkgs/main/linux-64::libuuid-1.41.5-h5eee18b_0
  libxcb             pkgs/main/linux-64::libxcb-1.17.0-h9b100fa_0
  libzlib            pkgs/main/linux-64::libzlib-1.3.1-hb25bd0a_0
  ncurses            pkgs/main/linux-64::ncurses-6.5-h7934f7d_0
  openssl            pkgs/main/linux-64::openssl-3.5.5-h1b28b03_0
  packaging          pkgs/main/linux-64::packaging-25.0-py310h06a4308_1
  pip                pkgs/main/noarch::pip-26.0.1-pyhc872135_0
  pthread-stubs      pkgs/main/linux-64::pthread-stubs-0.3-h0ce48e5_1
  python             pkgs/main/linux-64::python-3.10.20-h741d88c_0
  readline           pkgs/main/linux-64::readline-8.3-hc2a1206_0
  setuptools         pkgs/main/linux-64::setuptools-80.10.2-py310h06a4308_0
  sqlite             pkgs/main/linux-64::sqlite-3.51.2-h3e8d24a_0
  tk                 pkgs/main/linux-64::tk-8.6.15-h54e0aa7_0
  tzdata             pkgs/main/noarch::tzdata-2026a-he532380_0
  wheel              pkgs/main/linux-64::wheel-0.46.3-py310h06a4308_0
  xorg-libx11        pkgs/main/linux-64::xorg-libx11-1.8.12-h9b100fa_1
  xorg-libxau        pkgs/main/linux-64::xorg-libxau-1.0.12-h9b100fa_0
  xorg-libxdmcp      pkgs/main/linux-64::xorg-libxdmcp-1.1.5-h9b100fa_0
  xorg-xorgproto     pkgs/main/linux-64::xorg-xorgproto-2024.1-h5eee18b_1
  xz                 pkgs/main/linux-64::xz-5.8.2-h448239c_0
  zlib               pkgs/main/linux-64::zlib-1.3.1-hb25bd0a_0



Downloading and Extracting Packages: ...working... done
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate mfcd310
#
# To deactivate an active environment, use
#
#     $ conda deactivate

Requirement already satisfied: pip in /usr/local/miniconda/envs/vcd310/lib/python3.10/site-packages (26.0.1)
Requirement already satisfied: setuptools in /usr/local/miniconda/envs/vcd310/lib/python3.10/site-packages (80.10.2)
Collecting setuptools
  Downloading setuptools-82.0.1-py3-none-any.whl.metadata (6.5 kB)
Requirement already satisfied: wheel in /usr/local/miniconda/envs/vcd310/lib/python3.10/site-packages (0.46.3)
Requirement already satisfied: packaging>=24.0 in /usr/local/miniconda/envs/vcd310/lib/python3.10/site-packages (from wheel) (25.0)
Downloading setuptools-82.0.1-py3-none-any.whl (1.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 27.0 MB/s  0:00:00
Installing collected packages: setuptools
  Attempting uninstall: setuptools
    Found existing installation: setuptools 80.10.2
    Uninstalling setuptools-80.10.2:
      Successfully uninstalled setuptools-80.10.2
Successfully installed setuptools-82.0.1
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu128
Collecting torch==2.7.0+cu128 (from -r /content/VCD_project/requirements.txt (line 5))
  Downloading https://download.pytorch.org/whl/cu128/torch-2.7.0%2Bcu128-cp310-cp310-manylinux_2_28_x86_64.whl.metadata (29 kB)
Collecting torchvision==0.22.0+cu128 (from -r /content/VCD_project/requirements.txt (line 6))
  Downloading https://download.pytorch.org/whl/cu128/torchvision-0.22.0%2Bcu128-cp310-cp310-manylinux_2_28_x86_64.whl.metadata (6.1 kB)
Collecting torchaudio==2.7.0+cu128 (from -r /content/VCD_project/requirements.txt (line 7))
  Downloading https://download-r2.pytorch.org/whl/cu128/torchaudio-2.7.0%2Bcu128-cp310-cp310-manylinux_2_28_x86_64.whl.metadata (6.6 kB)
Collecting xformers>=0.0.30 (from -r /content/VCD_project/requirements.txt (line 8))
  Downloading https://download.pytorch.org/whl/cu128/xformers-0.0.35-py39-none-manylinux_2_28_x86_64.whl.metadata (1.2 kB)
Collecting triton==3.3.0 (from -r /content/VCD_project/requirements.txt (line 9))
  Downloading https://download.pytorch.org/whl/triton-3.3.0-cp310-cp310-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (1.5 kB)
Collecting numpy<2.0.0,>=1.24.0 (from -r /content/VCD_project/requirements.txt (line 13))
  Downloading numpy-1.26.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
Collecting pydantic==2.11.0 (from -r /content/VCD_project/requirements.txt (line 14))
  Downloading pydantic-2.11.0-py3-none-any.whl.metadata (63 kB)
Collecting pandas==2.2.2 (from -r /content/VCD_project/requirements.txt (line 15))
  Downloading pandas-2.2.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (19 kB)
Collecting ipython<8.19.0,>=8.12.0 (from -r /content/VCD_project/requirements.txt (line 16))
  Downloading ipython-8.18.1-py3-none-any.whl.metadata (6.0 kB)
Collecting fastapi<1.0.0,>=0.124.1 (from -r /content/VCD_project/requirements.txt (line 19))
  Downloading fastapi-0.135.1-py3-none-any.whl.metadata (30 kB)
Collecting starlette<1.0.0,>=0.49.1 (from -r /content/VCD_project/requirements.txt (line 20))
  Downloading starlette-0.52.1-py3-none-any.whl.metadata (6.3 kB)
Collecting typing_extensions>=4.14.0 (from -r /content/VCD_project/requirements.txt (line 21))
  Downloading https://download.pytorch.org/whl/typing_extensions-4.15.0-py3-none-any.whl.metadata (3.3 kB)
Collecting bitsandbytes~=0.45.2 (from -r /content/VCD_project/requirements.txt (line 24))
  Downloading bitsandbytes-0.45.5-py3-none-manylinux_2_24_x86_64.whl.metadata (5.0 kB)
Collecting deepspeed~=0.16.3 (from -r /content/VCD_project/requirements.txt (line 25))
  Downloading deepspeed-0.16.9.tar.gz (1.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 51.7 MB/s  0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting accelerate~=1.4.0 (from -r /content/VCD_project/requirements.txt (line 26))
  Downloading accelerate-1.4.0-py3-none-any.whl.metadata (19 kB)
Collecting peft~=0.14.0 (from -r /content/VCD_project/requirements.txt (line 27))
  Downloading peft-0.14.0-py3-none-any.whl.metadata (13 kB)
Collecting transformers~=4.49.0 (from -r /content/VCD_project/requirements.txt (line 28))
  Downloading transformers-4.49.0-py3-none-any.whl.metadata (44 kB)
Collecting timm~=1.0.14 (from -r /content/VCD_project/requirements.txt (line 29))
  Downloading timm-1.0.25-py3-none-any.whl.metadata (38 kB)
Collecting datasets~=3.5.0 (from -r /content/VCD_project/requirements.txt (line 30))
  Downloading datasets-3.5.1-py3-none-any.whl.metadata (19 kB)
Collecting safetensors~=0.4.5 (from -r /content/VCD_project/requirements.txt (line 31))
  Downloading safetensors-0.4.5-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.8 kB)
Collecting tokenizers~=0.21.0 (from -r /content/VCD_project/requirements.txt (line 32))
  Downloading tokenizers-0.21.4-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.7 kB)
Collecting sentencepiece~=0.2.0 (from -r /content/VCD_project/requirements.txt (line 33))
  Downloading sentencepiece-0.2.1-cp310-cp310-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (10 kB)
Collecting scipy<1.14.0,>=1.10.0 (from -r /content/VCD_project/requirements.txt (line 34))
  Downloading scipy-1.13.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (60 kB)
Collecting scikit-learn~=1.6.1 (from -r /content/VCD_project/requirements.txt (line 35))
  Downloading scikit_learn-1.6.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (18 kB)
Collecting shortuuid==1.0.13 (from -r /content/VCD_project/requirements.txt (line 36))
  Downloading shortuuid-1.0.13-py3-none-any.whl.metadata (5.8 kB)
Collecting pillow~=11.1.0 (from -r /content/VCD_project/requirements.txt (line 37))
  Downloading pillow-11.1.0-cp310-cp310-manylinux_2_28_x86_64.whl.metadata (9.1 kB)
Collecting tqdm~=4.67.1 (from -r /content/VCD_project/requirements.txt (line 38))
  Downloading tqdm-4.67.3-py3-none-any.whl.metadata (57 kB)
Collecting nltk~=3.9.1 (from -r /content/VCD_project/requirements.txt (line 39))
  Downloading nltk-3.9.3-py3-none-any.whl.metadata (3.2 kB)
Collecting joblib~=1.4.2 (from -r /content/VCD_project/requirements.txt (line 40))
  Downloading joblib-1.4.2-py3-none-any.whl.metadata (5.4 kB)
Collecting filelock~=3.16.1 (from -r /content/VCD_project/requirements.txt (line 41))
  Downloading filelock-3.16.1-py3-none-any.whl.metadata (2.9 kB)
Collecting packaging~=24.2 (from -r /content/VCD_project/requirements.txt (line 42))
  Downloading packaging-24.2-py3-none-any.whl.metadata (3.2 kB)
Collecting requests~=2.32.3 (from -r /content/VCD_project/requirements.txt (line 43))
  Downloading requests-2.32.5-py3-none-any.whl.metadata (4.9 kB)
Collecting Jinja2~=3.1.5 (from -r /content/VCD_project/requirements.txt (line 44))
  Downloading https://download.pytorch.org/whl/jinja2-3.1.6-py3-none-any.whl.metadata (2.9 kB)
Collecting google~=3.0.0 (from -r /content/VCD_project/requirements.txt (line 45))
  Downloading google-3.0.0-py2.py3-none-any.whl.metadata (627 bytes)
Collecting Pygments~=2.19.1 (from -r /content/VCD_project/requirements.txt (line 46))
  Downloading pygments-2.19.2-py3-none-any.whl.metadata (2.5 kB)
Collecting regex~=2024.11.6 (from -r /content/VCD_project/requirements.txt (line 47))
  Downloading regex-2024.11.6-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (40 kB)
Collecting jieba~=0.42.1 (from -r /content/VCD_project/requirements.txt (line 48))
  Downloading jieba-0.42.1.tar.gz (19.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.2/19.2 MB 221.4 MB/s  0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting Levenshtein~=0.26.1 (from -r /content/VCD_project/requirements.txt (line 49))
  Downloading levenshtein-0.26.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.2 kB)
Collecting beautifulsoup4~=4.13.3 (from -r /content/VCD_project/requirements.txt (line 50))
  Downloading beautifulsoup4-4.13.5-py3-none-any.whl.metadata (3.8 kB)
Collecting pytesseract~=0.3.13 (from -r /content/VCD_project/requirements.txt (line 51))
  Downloading pytesseract-0.3.13-py3-none-any.whl.metadata (11 kB)
Collecting einops~=0.8.1 (from -r /content/VCD_project/requirements.txt (line 52))
  Downloading einops-0.8.2-py3-none-any.whl.metadata (13 kB)
Collecting PyYAML~=6.0.2 (from -r /content/VCD_project/requirements.txt (line 53))
  Downloading pyyaml-6.0.3-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (2.4 kB)
Collecting rich~=13.9.4 (from -r /content/VCD_project/requirements.txt (line 54))
  Downloading rich-13.9.4-py3-none-any.whl.metadata (18 kB)
Collecting uvicorn~=0.34.0 (from -r /content/VCD_project/requirements.txt (line 55))
  Downloading uvicorn-0.34.3-py3-none-any.whl.metadata (6.5 kB)
Collecting optuna~=4.3.0 (from -r /content/VCD_project/requirements.txt (line 56))
  Downloading optuna-4.3.0-py3-none-any.whl.metadata (17 kB)
Collecting urllib3~=2.3.0 (from -r /content/VCD_project/requirements.txt (line 57))
  Downloading urllib3-2.3.0-py3-none-any.whl.metadata (6.5 kB)
Collecting pytest~=8.3.4 (from -r /content/VCD_project/requirements.txt (line 58))
  Downloading pytest-8.3.5-py3-none-any.whl.metadata (7.6 kB)
Collecting h5py~=3.12.1 (from -r /content/VCD_project/requirements.txt (line 59))
  Downloading h5py-3.12.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.5 kB)
Collecting msgpack~=1.1.0 (from -r /content/VCD_project/requirements.txt (line 60))
  Downloading msgpack-1.1.2-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (8.1 kB)
Collecting sympy>=1.13.3 (from torch==2.7.0+cu128->-r /content/VCD_project/requirements.txt (line 5))
  Downloading sympy-1.14.0-py3-none-any.whl.metadata (12 kB)

In [5]:
import os
import subprocess
import shutil

# --- Configuration ---
DATASET_DIR = "/content/datasets/coco"
VAL_DIR = os.path.join(DATASET_DIR, "val2014")
ZIP_FILE = os.path.join(DATASET_DIR, "val2014.zip")
ZIP_URL = "http://images.cocodataset.org/zips/val2014.zip"

# 1. Create directory structure
os.makedirs(DATASET_DIR, exist_ok=True)

# 2. Download and Unzip if val2014 doesn't exist
if not os.path.exists(VAL_DIR):
    print(f"Downloading COCO val2014 to {DATASET_DIR}...")
    # Using subprocess for wget/unzip to handle large file streams efficiently
    subprocess.run(["wget", "-q", ZIP_URL, "-O", ZIP_FILE], check=True)
    
    print("Unzipping dataset...this will take about 2 min")
    subprocess.run(["unzip", "-q", ZIP_FILE, "-d", DATASET_DIR], check=True)
    
    # Optional: Clean up zip to save space on Colab
    os.remove(ZIP_FILE)
    print("Download and extraction complete.")
else:
    print("COCO val2014 already exists. Skipping download.")

# 3. Verify: Print first 8 lines of directory listing
print("\n--- Directory Preview (val2014) ---")
files = sorted(os.listdir(VAL_DIR))
for f in files[:8]:
    print(f)

Downloading COCO val2014 to /content/datasets/coco...
Unzipping dataset...this will take about 2 min
Download and extraction complete.

--- Directory Preview (val2014) ---
COCO_val2014_000000000042.jpg
COCO_val2014_000000000073.jpg
COCO_val2014_000000000074.jpg
COCO_val2014_000000000133.jpg
COCO_val2014_000000000136.jpg
COCO_val2014_000000000139.jpg
COCO_val2014_000000000143.jpg
COCO_val2014_000000000164.jpg

In [36]:
import os
import subprocess
from pathlib import Path

PYBIN_PATH = '/tmp/mytasks_python_bin.txt'
if not Path(PYBIN_PATH).exists():
    raise FileNotFoundError(f'Missing {PYBIN_PATH}. Run the conda setup cell first.')
PYBIN = Path(PYBIN_PATH).read_text().strip()

MODEL_PATH = 'liuhaotian/llava-v1.5-7b'
COCO_VAL = '/content/datasets/coco/val2014'
SEED = '55'
ROOT = '/content/VCD_project'
ORIG = f'{ROOT}/originalProject'

# Preflight checks for clearer errors
if not Path(ORIG, 'experiments').is_dir():
    raise FileNotFoundError(f'Missing originalProject/experiments at {ORIG}/experiments')
if not Path(COCO_VAL).is_dir():
    raise FileNotFoundError(f'Missing COCO val2014 at {COCO_VAL}')

env = os.environ.copy()
env['PYTHON_BIN'] = PYBIN
cmd = ['bash', '/content/VCD_project/myTasks/run_table1.sh', MODEL_PATH, COCO_VAL, SEED]
print('Running:', ' '.join(cmd))
result = subprocess.run(cmd, env=env, text=True, capture_output=True)
print(result.stdout)
if result.returncode != 0:
    print(result.stderr)
    raise RuntimeError(f'run_table1.sh failed with code {result.returncode}')

Running: bash /content/VCD_project/myTasks/run_table1.sh liuhaotian/llava-v1.5-7b /content/datasets/coco/val2014 55
Running split=random method=regular
Precision: 0.919931856899489
Recall: 0.72
F1: 0.8077786088257293
Accuracy: 0.8286666666666667
yes: 0.3913333333333333
unknow: 0.0
Saved: /content/VCD_project/myTasks/output/llava15_coco_pope_random_answers_regular_seed55.jsonl
Saved: /content/VCD_project/myTasks/output/metrics_random_regular_seed55.txt
Running split=random method=vcd
Precision: 0.9369369369369369
Recall: 0.7626666666666667
F1: 0.8408673281881661
Accuracy: 0.8556666666666667
yes: 0.407
unknow: 0.0
Saved: /content/VCD_project/myTasks/output/llava15_coco_pope_random_answers_vcd_seed55.jsonl
Saved: /content/VCD_project/myTasks/output/metrics_random_vcd_seed55.txt
Running split=popular method=regular
Precision: 0.8794788273615635
Recall: 0.72
F1: 0.7917888563049853
Accuracy: 0.8106666666666666
yes: 0.4093333333333333
unknow: 0.0
Saved: /content/VCD_project/myTasks/output/llava15_coco_pope_popular_answers_regular_seed55.jsonl
Saved: /content/VCD_project/myTasks/output/metrics_popular_regular_seed55.txt
Running split=popular method=vcd
Precision: 0.8930523028883685
Recall: 0.7626666666666667
F1: 0.8227256382596189
Accuracy: 0.8356666666666667
yes: 0.427
unknow: 0.0
Saved: /content/VCD_project/myTasks/output/llava15_coco_pope_popular_answers_vcd_seed55.jsonl
Saved: /content/VCD_project/myTasks/output/metrics_popular_vcd_seed55.txt
| Split | Method | Accuracy | Precision | Recall | F1 |
|---|---|---:|---:|---:|---:|
| random | regular | 0.8287 | 0.9199 | 0.7200 | 0.8078 |
| random | vcd | 0.8557 | 0.9369 | 0.7627 | 0.8409 |
| popular | regular | 0.8107 | 0.8795 | 0.7200 | 0.7918 |
| popular | vcd | 0.8357 | 0.8931 | 0.7627 | 0.8227 |

In [6]:
import subprocess
from pathlib import Path

# --- Setup Paths ---
PYBIN_PATH = '/tmp/mytasks_python_bin_mfcd.txt'
if not Path(PYBIN_PATH).exists():
    raise FileNotFoundError(f'Missing {PYBIN_PATH}. Run the conda setup cell first.')

PYBIN = Path(PYBIN_PATH).read_text().strip()
DRIVER_PATH = Path('/tmp/mfcd_driver.py')

# --- Optimized MFCD Driver Script ---
mfcd_driver = """
import os
import sys
import json
import torch
import gc
from pathlib import Path
from PIL import Image
from torch.utils.data import Dataset

# --- Configuration ---
ROOT = '/content/VCD_project'
ORIG = f'{ROOT}/originalProject'
MFCD = f'{ROOT}/originalMFCD/mfcd'
COCO_VAL = '/content/datasets/coco/val2014'
MODEL_PATH = 'llava-hf/llava-1.5-7b-hf'
OUT_DIR = f'{ROOT}/myTasks/output'

# MFCD Parameters
MFC_CONFIG = {
    'mfc_high_alpha': 1.0,
    'mfc_low_alpha': 1.0,
    'mfc_beta': 0.3,
    'mfc_high_pass_cutoff': 0.1,
    'mfc_low_pass_cutoff': 0.9,
    'mfc_filter_type': 'gaussian'
}

# Add MFCD to path
if MFCD not in sys.path:
    sys.path.insert(0, MFCD)

from eval_utils import prepare_for_generate, generate_responses, batch_prepare_data
from eval_utils import MODEL_INFOS
from eval.pope.eval import eval as pope_eval, recorder

class POPELocal(Dataset):
    def __init__(self, json_path, image_root):
        with open(json_path, 'r') as f:
            self.rows = [json.loads(line) for line in f]
        self.image_root = Path(image_root)

    def __len__(self):
        return len(self.rows)

    def __getitem__(self, idx):
        row = self.rows[idx]
        img = Image.open(self.image_root / row['image']).convert('RGB')
        return {
            'question': row['text'],
            'image': img,
            'label': row['label'].lower()
        }

def run_mfcd(pope_type):
    device = torch.device('cuda:0')
    
    class Args: pass
    args = Args()
    args.model_name_or_path = MODEL_PATH
    args.model_type = 'llava-1.5'
    args.num_workers = 4
    args.eval_batch_size = 16  # Optimized for Blackwell 96GB VRAM
    args.device = 'cuda:0'
    args.temperature = 1.2
    args.top_p = 1.0
    args.top_k = 50
    args.max_new_tokens = 2048
    
    # Map MFCD Config
    for k, v in MFC_CONFIG.items():
        setattr(args, k, v)
    args.mfc_jsd = False
    args.mfc_entropy = False

    print(f"\\n--- Starting MFCD: {pope_type} ---")
    model_info = MODEL_INFOS['llava-1.5']
    
    # Initialize Processor
    processor, generation_config, _ = prepare_for_generate(args=args, model_info=model_info, device=device)

    # Prepare Data
    pope_json = f"{ORIG}/experiments/data/POPE/coco/coco_pope_{pope_type}.json"
    dataset = POPELocal(pope_json, COCO_VAL)
    prompts = batch_prepare_data(args=args, dataset=dataset, processor=processor, 
                                 question_column_name='question', image_column_name='image')

    # Load Model
    model = model_info.model_class.from_pretrained(
        MODEL_PATH, 
        torch_dtype=torch.float16, # Ensure FP16 for Blackwell speed
        **model_info.model_config
    ).to(device)

    # Inference
    responses = generate_responses(model=model, processor=processor, prompts=prompts, generation_config=generation_config)

    # Eval
    labels = [1 if d['label'] == 'yes' else 0 for d in dataset]
    preds = recorder(responses)
    results = pope_eval(preds, labels)
    
    # Cleanup to prevent OOM on next run
    del model
    del processor
    gc.collect()
    torch.cuda.empty_cache()
    
    return results

# Execution
os.makedirs(OUT_DIR, exist_ok=True)
for p_type in ['random', 'popular']:
    res = run_mfcd(p_type)
    with open(os.path.join(OUT_DIR, f'mfcd_{p_type}.json'), 'w') as f:
        json.dump(res, f, indent=2)
    print(f"Results for {p_type}: {res}")
"""

# --- Run Driver ---
DRIVER_PATH.write_text(mfcd_driver)
print(f'Executing MFCD on Blackwell GPU using: {PYBIN}')

# Using Popen to stream logs in real-time
process = subprocess.Popen([PYBIN, str(DRIVER_PATH)], stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)

for line in process.stdout:
    print(line, end='')

process.wait()

if process.returncode != 0:
    raise RuntimeError(f'MFCD driver failed with code {process.returncode}')

Executing MFCD on Blackwell GPU using: /usr/local/miniconda/envs/mfcd310/bin/python

--- Starting MFCD: random ---

Applying chat template:   0%|          | 0/188 [00:00<?, ?it/s]
Applying chat template:   2%|▏         | 4/188 [00:00<00:05, 36.02it/s]
Applying chat template:   4%|▍         | 8/188 [00:00<00:04, 38.24it/s]
Applying chat template:   6%|▋         | 12/188 [00:00<00:04, 38.86it/s]
Applying chat template:   9%|▉         | 17/188 [00:00<00:04, 40.49it/s]
Applying chat template:  12%|█▏        | 22/188 [00:00<00:04, 36.42it/s]
Applying chat template:  14%|█▍        | 26/188 [00:00<00:04, 35.76it/s]
Applying chat template:  16%|█▌        | 30/188 [00:00<00:04, 36.56it/s]
Applying chat template:  18%|█▊        | 34/188 [00:00<00:04, 34.66it/s]
Applying chat template:  20%|██        | 38/188 [00:01<00:04, 35.76it/s]
Applying chat template:  22%|██▏       | 42/188 [00:01<00:04, 35.84it/s]
Applying chat template:  24%|██▍       | 46/188 [00:01<00:04, 34.65it/s]
Applying chat template:  27%|██▋       | 50/188 [00:01<00:03, 35.53it/s]
Applying chat template:  29%|██▊       | 54/188 [00:01<00:03, 35.18it/s]
Applying chat template:  31%|███▏      | 59/188 [00:01<00:03, 37.04it/s]
Applying chat template:  34%|███▎      | 63/188 [00:01<00:03, 37.36it/s]
Applying chat template:  36%|███▌      | 67/188 [00:01<00:03, 37.33it/s]
Applying chat template:  38%|███▊      | 71/188 [00:01<00:03, 36.32it/s]
Applying chat template:  40%|███▉      | 75/188 [00:02<00:03, 35.67it/s]
Applying chat template:  42%|████▏     | 79/188 [00:02<00:02, 36.81it/s]
Applying chat template:  44%|████▍     | 83/188 [00:02<00:02, 35.71it/s]
Applying chat template:  46%|████▋     | 87/188 [00:02<00:02, 34.16it/s]
Applying chat template:  48%|████▊     | 91/188 [00:02<00:02, 33.41it/s]
Applying chat template:  51%|█████     | 95/188 [00:02<00:02, 33.47it/s]
Applying chat template:  53%|█████▎    | 99/188 [00:02<00:02, 33.98it/s]
Applying chat template:  55%|█████▍    | 103/188 [00:02<00:02, 33.16it/s]
Applying chat template:  57%|█████▋    | 107/188 [00:03<00:02, 34.30it/s]
Applying chat template:  59%|█████▉    | 111/188 [00:03<00:02, 35.51it/s]
Applying chat template:  61%|██████    | 115/188 [00:03<00:02, 33.60it/s]
Applying chat template:  63%|██████▎   | 119/188 [00:03<00:01, 34.57it/s]
Applying chat template:  65%|██████▌   | 123/188 [00:03<00:01, 35.17it/s]
Applying chat template:  68%|██████▊   | 127/188 [00:03<00:01, 35.23it/s]
Applying chat template:  70%|██████▉   | 131/188 [00:03<00:01, 34.62it/s]
Applying chat template:  72%|███████▏  | 135/188 [00:03<00:01, 35.42it/s]
Applying chat template:  74%|███████▍  | 139/188 [00:03<00:01, 36.56it/s]
Applying chat template:  76%|███████▌  | 143/188 [00:04<00:01, 36.85it/s]
Applying chat template:  78%|███████▊  | 147/188 [00:04<00:01, 37.20it/s]
Applying chat template:  80%|████████  | 151/188 [00:04<00:01, 36.86it/s]
Applying chat template:  82%|████████▏ | 155/188 [00:04<00:00, 36.35it/s]
Applying chat template:  85%|████████▍ | 159/188 [00:04<00:00, 36.08it/s]
Applying chat template:  87%|████████▋ | 163/188 [00:04<00:00, 37.16it/s]
Applying chat template:  89%|████████▉ | 167/188 [00:04<00:00, 36.79it/s]
Applying chat template:  91%|█████████ | 171/188 [00:04<00:00, 37.27it/s]
Applying chat template:  93%|█████████▎| 175/188 [00:04<00:00, 36.71it/s]
Applying chat template:  95%|█████████▌| 179/188 [00:04<00:00, 36.15it/s]
Applying chat template:  97%|█████████▋| 183/188 [00:05<00:00, 37.14it/s]
Applying chat template:  99%|█████████▉| 187/188 [00:05<00:00, 37.09it/s]
Applying chat template: 100%|██████████| 188/188 [00:05<00:00, 36.01it/s]

Processing batch data:   0%|          | 0/188 [00:00<?, ?it/s]
Processing batch data:   2%|▏         | 4/188 [00:00<00:05, 32.00it/s]
Processing batch data:   4%|▍         | 8/188 [00:03<01:26,  2.09it/s]
Processing batch data:   6%|▋         | 12/188 [00:03<00:58,  3.01it/s]
Processing batch data:   9%|▊         | 16/188 [00:04<00:40,  4.25it/s]
Processing batch data:  11%|█         | 20/188 [00:04<00:31,  5.35it/s]
Processing batch data:  13%|█▎        | 24/188 [00:05<00:25,  6.31it/s]
Processing batch data:  15%|█▍        | 28/188 [00:05<00:22,  7.12it/s]
Processing batch data:  17%|█▋        | 32/188 [00:05<00:19,  8.06it/s]
Processing batch data:  19%|█▉        | 36/188 [00:06<00:17,  8.51it/s]
Processing batch data:  21%|██▏       | 40/188 [00:06<00:18,  8.10it/s]
Processing batch data:  23%|██▎       | 44/188 [00:07<00:16,  8.77it/s]
Processing batch data:  26%|██▌       | 48/188 [00:07<00:15,  9.24it/s]
Processing batch data:  28%|██▊       | 52/188 [00:08<00:15,  8.66it/s]
Processing batch data:  30%|██▉       | 56/188 [00:08<00:14,  9.36it/s]
Processing batch data:  32%|███▏      | 60/188 [00:08<00:14,  8.75it/s]
Processing batch data:  34%|███▍      | 64/188 [00:09<00:13,  9.45it/s]
Processing batch data:  36%|███▌      | 68/188 [00:09<00:13,  9.16it/s]
Processing batch data:  38%|███▊      | 72/188 [00:10<00:12,  9.41it/s]
Processing batch data:  40%|████      | 76/188 [00:10<00:12,  8.73it/s]
Processing batch data:  43%|████▎     | 80/188 [00:11<00:11,  9.25it/s]
Processing batch data:  45%|████▍     | 84/188 [00:11<00:11,  8.88it/s]
Processing batch data:  47%|████▋     | 88/188 [00:11<00:10,  9.24it/s]
Processing batch data:  49%|████▉     | 92/188 [00:12<00:10,  9.31it/s]
Processing batch data:  51%|█████     | 96/188 [00:12<00:09,  9.29it/s]
Processing batch data:  53%|█████▎    | 100/188 [00:13<00:09,  9.39it/s]
Processing batch data:  55%|█████▌    | 104/188 [00:13<00:08,  9.78it/s]
Processing batch data:  57%|█████▋    | 108/188 [00:14<00:09,  8.73it/s]
Processing batch data:  60%|█████▉    | 112/188 [00:14<00:08,  8.95it/s]
Processing batch data:  62%|██████▏   | 116/188 [00:14<00:07,  9.48it/s]
Processing batch data:  64%|██████▍   | 120/188 [00:15<00:07,  9.09it/s]
Processing batch data:  66%|██████▌   | 124/188 [00:15<00:06,  9.31it/s]
Processing batch data:  68%|██████▊   | 128/188 [00:16<00:06,  9.55it/s]
Processing batch data:  70%|███████   | 132/188 [00:16<00:05,  9.61it/s]
Processing batch data:  72%|███████▏  | 136/188 [00:17<00:05,  9.25it/s]
Processing batch data:  74%|███████▍  | 140/188 [00:17<00:04,  9.72it/s]
Processing batch data:  77%|███████▋  | 144/188 [00:17<00:04,  9.71it/s]
Processing batch data:  79%|███████▊  | 148/188 [00:18<00:04,  9.12it/s]
Processing batch data:  81%|████████  | 152/188 [00:18<00:03,  9.46it/s]
Processing batch data:  83%|████████▎ | 156/188 [00:19<00:03,  9.78it/s]
Processing batch data:  85%|████████▌ | 160/188 [00:19<00:03,  9.00it/s]
Processing batch data:  87%|████████▋ | 164/188 [00:20<00:02,  9.59it/s]
Processing batch data:  89%|████████▉ | 168/188 [00:20<00:02,  9.91it/s]
Processing batch data:  91%|█████████▏| 172/188 [00:20<00:01,  9.31it/s]
Processing batch data:  94%|█████████▎| 176/188 [00:21<00:01,  9.49it/s]
Processing batch data:  96%|█████████▌| 180/188 [00:21<00:00,  9.95it/s]
Processing batch data:  98%|█████████▊| 184/188 [00:22<00:00,  8.91it/s]
Processing batch data: 100%|██████████| 188/188 [00:22<00:00,  9.56it/s]
Processing batch data: 100%|██████████| 188/188 [00:22<00:00,  8.33it/s]

Fetching 3 files:   0%|          | 0/3 [00:00<?, ?it/s]
Fetching 3 files:  33%|███▎      | 1/3 [00:43<01:27, 43.55s/it]
Fetching 3 files: 100%|██████████| 3/3 [00:43<00:00, 14.52s/it]

Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]
Loading checkpoint shards:  67%|██████▋   | 2/3 [00:00<00:00,  9.05it/s]
Loading checkpoint shards: 100%|██████████| 3/3 [00:00<00:00,  7.64it/s]
Loading checkpoint shards: 100%|██████████| 3/3 [00:00<00:00,  7.88it/s]

Generating responses:   0%|          | 0/188 [00:00<?, ?it/s]
Generating responses:   1%|          | 1/188 [00:04<13:27,  4.32s/it]
Generating responses:   1%|          | 2/188 [00:08<12:51,  4.15s/it]
Generating responses:   2%|▏         | 3/188 [00:11<11:55,  3.87s/it]
Generating responses:   2%|▏         | 4/188 [00:15<11:47,  3.84s/it]
Generating responses:   3%|▎         | 5/188 [00:19<11:34,  3.79s/it]
Generating responses:   3%|▎         | 6/188 [00:23<11:24,  3.76s/it]
Generating responses:   4%|▎         | 7/188 [00:27<11:33,  3.83s/it]
Generating responses:   4%|▍         | 8/188 [00:30<11:09,  3.72s/it]
Generating responses:   5%|▍         | 9/188 [00:34<11:02,  3.70s/it]
Generating responses:   5%|▌         | 10/188 [00:37<10:44,  3.62s/it]
Generating responses:   6%|▌         | 11/188 [00:40<10:24,  3.53s/it]
Generating responses:   6%|▋         | 12/188 [00:45<10:56,  3.73s/it]
Generating responses:   7%|▋         | 13/188 [00:48<10:54,  3.74s/it]
Generating responses:   7%|▋         | 14/188 [00:52<10:35,  3.65s/it]
Generating responses:   8%|▊         | 15/188 [00:55<10:23,  3.60s/it]
Generating responses:   9%|▊         | 16/188 [00:59<10:14,  3.57s/it]
Generating responses:   9%|▉         | 17/188 [01:03<10:20,  3.63s/it]
Generating responses:  10%|▉         | 18/188 [01:06<10:18,  3.64s/it]
Generating responses:  10%|█         | 19/188 [01:10<10:27,  3.71s/it]
Generating responses:  11%|█         | 20/188 [01:14<10:29,  3.75s/it]
Generating responses:  11%|█         | 21/188 [01:18<10:27,  3.76s/it]
Generating responses:  12%|█▏        | 22/188 [01:21<10:05,  3.65s/it]
Generating responses:  12%|█▏        | 23/188 [01:25<09:47,  3.56s/it]
Generating responses:  13%|█▎        | 24/188 [01:28<09:46,  3.58s/it]
Generating responses:  13%|█▎        | 25/188 [01:32<09:34,  3.52s/it]
Generating responses:  14%|█▍        | 26/188 [01:35<09:38,  3.57s/it]
Generating responses:  14%|█▍        | 27/188 [01:39<09:31,  3.55s/it]
Generating responses:  15%|█▍        | 28/188 [01:42<09:36,  3.60s/it]
Generating responses:  15%|█▌        | 29/188 [01:46<09:40,  3.65s/it]
Generating responses:  16%|█▌        | 30/188 [01:50<09:32,  3.63s/it]
Generating responses:  16%|█▋        | 31/188 [01:54<10:15,  3.92s/it]
Generating responses:  17%|█▋        | 32/188 [01:58<09:44,  3.75s/it]
Generating responses:  18%|█▊        | 33/188 [02:02<09:42,  3.76s/it]
Generating responses:  18%|█▊        | 34/188 [02:05<09:27,  3.68s/it]
Generating responses:  19%|█▊        | 35/188 [02:09<09:37,  3.78s/it]
Generating responses:  19%|█▉        | 36/188 [02:13<09:46,  3.86s/it]
Generating responses:  20%|█▉        | 37/188 [02:17<09:26,  3.75s/it]
Generating responses:  20%|██        | 38/188 [02:20<09:19,  3.73s/it]
Generating responses:  21%|██        | 39/188 [02:24<09:29,  3.82s/it]
Generating responses:  21%|██▏       | 40/188 [02:28<09:21,  3.79s/it]
Generating responses:  22%|██▏       | 41/188 [02:32<09:23,  3.83s/it]
Generating responses:  22%|██▏       | 42/188 [02:36<09:17,  3.82s/it]
Generating responses:  23%|██▎       | 43/188 [02:39<09:09,  3.79s/it]
Generating responses:  23%|██▎       | 44/188 [02:43<08:51,  3.69s/it]
Generating responses:  24%|██▍       | 45/188 [02:47<08:49,  3.70s/it]
Generating responses:  24%|██▍       | 46/188 [02:50<08:41,  3.68s/it]
Generating responses:  25%|██▌       | 47/188 [02:54<08:26,  3.60s/it]
Generating responses:  26%|██▌       | 48/188 [02:57<08:26,  3.62s/it]
Generating responses:  26%|██▌       | 49/188 [03:01<08:29,  3.67s/it]
Generating responses:  27%|██▋       | 50/188 [03:05<08:33,  3.72s/it]
Generating responses:  27%|██▋       | 51/188 [03:09<08:34,  3.75s/it]
Generating responses:  28%|██▊       | 52/188 [03:12<08:22,  3.70s/it]
Generating responses:  28%|██▊       | 53/188 [03:16<08:20,  3.71s/it]
Generating responses:  29%|██▊       | 54/188 [03:20<08:22,  3.75s/it]
Generating responses:  29%|██▉       | 55/188 [03:24<08:13,  3.71s/it]
Generating responses:  30%|██▉       | 56/188 [03:28<08:25,  3.83s/it]
Generating responses:  30%|███       | 57/188 [03:32<08:26,  3.87s/it]
Generating responses:  31%|███       | 58/188 [03:36<08:25,  3.89s/it]
Generating responses:  31%|███▏      | 59/188 [03:39<08:19,  3.87s/it]
Generating responses:  32%|███▏      | 60/188 [03:43<08:10,  3.83s/it]
Generating responses:  32%|███▏      | 61/188 [03:47<07:54,  3.74s/it]
Generating responses:  33%|███▎      | 62/188 [03:50<07:40,  3.65s/it]
Generating responses:  34%|███▎      | 63/188 [03:54<07:57,  3.82s/it]
Generating responses:  34%|███▍      | 64/188 [03:58<07:52,  3.81s/it]
Generating responses:  35%|███▍      | 65/188 [04:02<07:53,  3.85s/it]
Generating responses:  35%|███▌      | 66/188 [04:06<07:57,  3.91s/it]
Generating responses:  36%|███▌      | 67/188 [04:10<07:48,  3.87s/it]
Generating responses:  36%|███▌      | 68/188 [04:14<07:35,  3.80s/it]
Generating responses:  37%|███▋      | 69/188 [04:18<07:47,  3.93s/it]
Generating responses:  37%|███▋      | 70/188 [04:22<07:42,  3.92s/it]
Generating responses:  38%|███▊      | 71/188 [04:26<07:41,  3.94s/it]
Generating responses:  38%|███▊      | 72/188 [04:29<07:26,  3.84s/it]
Generating responses:  39%|███▉      | 73/188 [04:33<07:08,  3.73s/it]
Generating responses:  39%|███▉      | 74/188 [04:36<06:55,  3.65s/it]
Generating responses:  40%|███▉      | 75/188 [04:40<06:47,  3.61s/it]
Generating responses:  40%|████      | 76/188 [04:43<06:50,  3.66s/it]
Generating responses:  41%|████      | 77/188 [04:47<06:54,  3.73s/it]
Generating responses:  41%|████▏     | 78/188 [04:51<06:54,  3.77s/it]
Generating responses:  42%|████▏     | 79/188 [04:55<06:47,  3.74s/it]
Generating responses:  43%|████▎     | 80/188 [04:59<06:43,  3.74s/it]
Generating responses:  43%|████▎     | 81/188 [05:02<06:29,  3.64s/it]
Generating responses:  44%|████▎     | 82/188 [05:06<06:28,  3.66s/it]
Generating responses:  44%|████▍     | 83/188 [05:10<06:36,  3.78s/it]
Generating responses:  45%|████▍     | 84/188 [05:13<06:26,  3.72s/it]
Generating responses:  45%|████▌     | 85/188 [05:17<06:23,  3.72s/it]
Generating responses:  46%|████▌     | 86/188 [05:21<06:29,  3.82s/it]
Generating responses:  46%|████▋     | 87/188 [05:25<06:28,  3.84s/it]
Generating responses:  47%|████▋     | 88/188 [05:29<06:17,  3.78s/it]
Generating responses:  47%|████▋     | 89/188 [05:33<06:15,  3.80s/it]
Generating responses:  48%|████▊     | 90/188 [05:36<06:08,  3.76s/it]
Generating responses:  48%|████▊     | 91/188 [05:40<06:07,  3.78s/it]
Generating responses:  49%|████▉     | 92/188 [05:44<06:08,  3.83s/it]
Generating responses:  49%|████▉     | 93/188 [05:48<05:58,  3.77s/it]
Generating responses:  50%|█████     | 94/188 [05:52<06:04,  3.87s/it]
Generating responses:  51%|█████     | 95/188 [05:56<06:02,  3.90s/it]
Generating responses:  51%|█████     | 96/188 [05:59<05:50,  3.81s/it]
Generating responses:  52%|█████▏    | 97/188 [06:03<05:40,  3.74s/it]
Generating responses:  52%|█████▏    | 98/188 [06:07<05:36,  3.74s/it]
Generating responses:  53%|█████▎    | 99/188 [06:11<05:42,  3.85s/it]
Generating responses:  53%|█████▎    | 100/188 [06:14<05:32,  3.78s/it]
Generating responses:  54%|█████▎    | 101/188 [06:18<05:24,  3.74s/it]
Generating responses:  54%|█████▍    | 102/188 [06:22<05:23,  3.77s/it]
Generating responses:  55%|█████▍    | 103/188 [06:25<05:16,  3.72s/it]
Generating responses:  55%|█████▌    | 104/188 [06:29<05:21,  3.82s/it]
Generating responses:  56%|█████▌    | 105/188 [06:34<05:35,  4.05s/it]
Generating responses:  56%|█████▋    | 106/188 [06:38<05:29,  4.02s/it]
Generating responses:  57%|█████▋    | 107/188 [06:42<05:18,  3.93s/it]
Generating responses:  57%|█████▋    | 108/188 [06:45<05:08,  3.85s/it]
Generating responses:  58%|█████▊    | 109/188 [06:49<05:09,  3.91s/it]
Generating responses:  59%|█████▊    | 110/188 [06:53<05:00,  3.86s/it]
Generating responses:  59%|█████▉    | 111/188 [06:57<04:54,  3.82s/it]
Generating responses:  60%|█████▉    | 112/188 [07:00<04:42,  3.71s/it]
Generating responses:  60%|██████    | 113/188 [07:04<04:37,  3.70s/it]
Generating responses:  61%|██████    | 114/188 [07:08<04:38,  3.76s/it]
Generating responses:  61%|██████    | 115/188 [07:12<04:32,  3.73s/it]
Generating responses:  62%|██████▏   | 116/188 [07:16<04:33,  3.80s/it]
Generating responses:  62%|██████▏   | 117/188 [07:19<04:25,  3.74s/it]
Generating responses:  63%|██████▎   | 118/188 [07:23<04:16,  3.66s/it]
Generating responses:  63%|██████▎   | 119/188 [07:26<04:12,  3.66s/it]
Generating responses:  64%|██████▍   | 120/188 [07:30<04:12,  3.72s/it]
Generating responses:  64%|██████▍   | 121/188 [07:34<04:10,  3.74s/it]
Generating responses:  65%|██████▍   | 122/188 [07:38<04:13,  3.85s/it]
Generating responses:  65%|██████▌   | 123/188 [07:42<04:07,  3.81s/it]
Generating responses:  66%|██████▌   | 124/188 [07:45<04:02,  3.79s/it]
Generating responses:  66%|██████▋   | 125/188 [07:49<03:58,  3.79s/it]
Generating responses:  67%|██████▋   | 126/188 [07:53<03:46,  3.66s/it]
Generating responses:  68%|██████▊   | 127/188 [07:56<03:42,  3.64s/it]
Generating responses:  68%|██████▊   | 128/188 [08:01<03:53,  3.88s/it]
Generating responses:  69%|██████▊   | 129/188 [08:04<03:44,  3.81s/it]
Generating responses:  69%|██████▉   | 130/188 [08:08<03:42,  3.83s/it]
Generating responses:  70%|██████▉   | 131/188 [08:12<03:33,  3.74s/it]
Generating responses:  70%|███████   | 132/188 [08:15<03:26,  3.69s/it]
Generating responses:  71%|███████   | 133/188 [08:19<03:27,  3.78s/it]
Generating responses:  71%|███████▏  | 134/188 [08:23<03:18,  3.69s/it]
Generating responses:  72%|███████▏  | 135/188 [08:26<03:16,  3.70s/it]
Generating responses:  72%|███████▏  | 136/188 [08:30<03:10,  3.66s/it]
Generating responses:  73%|███████▎  | 137/188 [08:34<03:10,  3.73s/it]
Generating responses:  73%|███████▎  | 138/188 [08:38<03:08,  3.76s/it]
Generating responses:  74%|███████▍  | 139/188 [08:42<03:05,  3.78s/it]
Generating responses:  74%|███████▍  | 140/188 [08:46<03:05,  3.87s/it]
Generating responses:  75%|███████▌  | 141/188 [08:50<03:06,  3.96s/it]
Generating responses:  76%|███████▌  | 142/188 [08:54<03:00,  3.92s/it]
Generating responses:  76%|███████▌  | 143/188 [08:57<02:53,  3.85s/it]
Generating responses:  77%|███████▋  | 144/188 [09:01<02:44,  3.75s/it]
Generating responses:  77%|███████▋  | 145/188 [09:05<02:40,  3.74s/it]
Generating responses:  78%|███████▊  | 146/188 [09:08<02:35,  3.71s/it]
Generating responses:  78%|███████▊  | 147/188 [09:12<02:26,  3.59s/it]
Generating responses:  79%|███████▊  | 148/188 [09:15<02:25,  3.65s/it]
Generating responses:  79%|███████▉  | 149/188 [09:19<02:21,  3.62s/it]
Generating responses:  80%|███████▉  | 150/188 [09:23<02:20,  3.70s/it]
Generating responses:  80%|████████  | 151/188 [09:26<02:16,  3.68s/it]
Generating responses:  81%|████████  | 152/188 [09:31<02:19,  3.88s/it]
Generating responses:  81%|████████▏ | 153/188 [09:34<02:12,  3.78s/it]
Generating responses:  82%|████████▏ | 154/188 [09:38<02:09,  3.82s/it]
Generating responses:  82%|████████▏ | 155/188 [09:42<02:04,  3.77s/it]
Generating responses:  83%|████████▎ | 156/188 [09:45<01:59,  3.73s/it]
Generating responses:  84%|████████▎ | 157/188 [09:49<01:53,  3.65s/it]
Generating responses:  84%|████████▍ | 158/188 [09:53<01:52,  3.75s/it]
Generating responses:  85%|████████▍ | 159/188 [09:57<01:52,  3.88s/it]
Generating responses:  85%|████████▌ | 160/188 [10:01<01:50,  3.93s/it]
Generating responses:  86%|████████▌ | 161/188 [10:05<01:41,  3.78s/it]
Generating responses:  86%|████████▌ | 162/188 [10:08<01:36,  3.73s/it]
Generating responses:  87%|████████▋ | 163/188 [10:12<01:32,  3.70s/it]
Generating responses:  87%|████████▋ | 164/188 [10:16<01:28,  3.71s/it]
Generating responses:  88%|████████▊ | 165/188 [10:19<01:25,  3.70s/it]
Generating responses:  88%|████████▊ | 166/188 [10:23<01:23,  3.77s/it]
Generating responses:  89%|████████▉ | 167/188 [10:27<01:19,  3.78s/it]
Generating responses:  89%|████████▉ | 168/188 [10:30<01:13,  3.70s/it]
Generating responses:  90%|████████▉ | 169/188 [10:35<01:12,  3.82s/it]
Generating responses:  90%|█████████ | 170/188 [10:38<01:08,  3.83s/it]
Generating responses:  91%|█████████ | 171/188 [10:42<01:05,  3.88s/it]
Generating responses:  91%|█████████▏| 172/188 [10:46<01:01,  3.85s/it]

In [10]:
import json
import re
from pathlib import Path
P1 = '/content/VCD_project/myTasks'
SEED = 55
out_dir = Path(f'{P1}/output')
def parse_metrics_txt(path: Path):
    text = path.read_text()
    def g(name):
        m = re.search(rf"^{name}:\s*([0-9.]+)", text, re.MULTILINE)
        return float(m.group(1)) if m else float('nan')
    return {
        'accuracy': g('Accuracy'),
        'precision': g('Precision'),
        'recall': g('Recall'),
        'f1': g('F1'),
    }
def parse_metrics_json(path: Path):
    data = json.loads(path.read_text())
    return {
        'accuracy': float(data.get('accuracy', float('nan'))),
        'precision': float(data.get('precision', float('nan'))),
        'recall': float(data.get('recall', float('nan'))),
        'f1': float(data.get('f1', float('nan'))),
    }
vcd_random = parse_metrics_txt(out_dir / f'metrics_random_vcd_seed{SEED}.txt')
vcd_popular = parse_metrics_txt(out_dir / f'metrics_popular_vcd_seed{SEED}.txt')
mfcd_random = parse_metrics_json(out_dir / 'mfcd_random.json')
mfcd_popular = parse_metrics_json(out_dir / 'mfcd_popular.json')
print('| Split | Method | Accuracy | Precision | Recall | F1 |')
print('|---|---|---:|---:|---:|---:|')
print(f"| random | VCD | {vcd_random['accuracy']:.4f} | {vcd_random['precision']:.4f} | {vcd_random['recall']:.4f} | {vcd_random['f1']:.4f} |")
print(f"| random | MFCD | {mfcd_random['accuracy']:.4f} | {mfcd_random['precision']:.4f} | {mfcd_random['recall']:.4f} | {mfcd_random['f1']:.4f} |")
print(f"| popular | VCD | {vcd_popular['accuracy']:.4f} | {vcd_popular['precision']:.4f} | {vcd_popular['recall']:.4f} | {vcd_popular['f1']:.4f} |")
print(f"| popular | MFCD | {mfcd_popular['accuracy']:.4f} | {mfcd_popular['precision']:.4f} | {mfcd_popular['recall']:.4f} | {mfcd_popular['f1']:.4f} |")

| Split | Method | Accuracy | Precision | Recall | F1 |
|---|---|---:|---:|---:|---:|
| random | VCD | 0.8557 | 0.9369 | 0.7627 | 0.8409 |
| random | MFCD | 0.8687 | 0.8540 | 0.8893 | nan |
| popular | VCD | 0.8357 | 0.8931 | 0.7627 | 0.8227 |
| popular | MFCD | 0.8267 | 0.7913 | 0.8873 | nan |

In [9]:
import subprocess
from pathlib import Path

# --- Setup Paths ---
PYBIN_PATH = '/tmp/mytasks_python_bin.txt'
if not Path(PYBIN_PATH).exists():
    raise FileNotFoundError(f'Missing {PYBIN_PATH}. Run the conda setup cell first.')

PYBIN = Path(PYBIN_PATH).read_text().strip()
DRIVER_PATH = Path('/tmp/vcd_driver.py')

# --- Clean VCD Driver Script ---
vcd_driver = """
import os
import sys
import torch
import gc
import subprocess
from pathlib import Path

# --- Configuration ---
ROOT = '/content/VCD_project'
ORIG = f'{ROOT}/originalProject'
EXP_DIR = f'{ORIG}/experiments'
OUT_DIR = f'{ROOT}/myTasks/output'
COCO_VAL = '/content/datasets/coco/val2014'
MODEL_PATH = 'liuhaotian/llava-v1.5-7b'
SEED = '55'

# VCD Hyperparameters
CD_ALPHA = "1.0"
CD_BETA = "0.2"
NOISE_STEP = "500"

os.makedirs(OUT_DIR, exist_ok=True)

def run_vcd_step(split, method):
    question_file = f"{EXP_DIR}/data/POPE/coco/coco_pope_{split}.json"
    answers_file = f"{OUT_DIR}/llava15_coco_pope_{split}_answers_{method}_seed{SEED}.jsonl"
    metrics_file = f"{OUT_DIR}/metrics_{split}_{method}_seed{SEED}.txt"

    print(f"\\n>>> STARTING: Split={split} | Method={method}")

    # 1. Run Inference
    cmd = [
        sys.executable, "./eval/object_hallucination_vqa_llava.py",
        "--model-path", MODEL_PATH,
        "--question-file", question_file,
        "--image-folder", COCO_VAL,
        "--answers-file", answers_file,
        "--seed", SEED
    ]

    if method == "vcd":
        cmd += ["--use_cd", "--cd_alpha", CD_ALPHA, "--cd_beta", CD_BETA, "--noise_step", NOISE_STEP]

    os.chdir(EXP_DIR)
    subprocess.run(cmd, check=True)

    # 2. Run POPE Eval (Creates the .txt file for your table parser)
    eval_cmd = [sys.executable, "./eval/eval_pope.py", "--gt_files", question_file, "--gen_files", answers_file]
    with open(metrics_file, "w") as f:
        subprocess.run(eval_cmd, stdout=f, check=True)
    
    # Blackwell Memory Management
    gc.collect()
    torch.cuda.empty_cache()

# Execute benchmarks
for split in ['random', 'popular']:
    for method in ['regular', 'vcd']:
        run_vcd_step(split, method)

print("\\n--- VCD Evaluation Complete. Files ready for comparison table. ---")
"""

# --- Execute Wrapper ---
DRIVER_PATH.write_text(vcd_driver)
print(f'Running VCD Benchmarks on Blackwell GPU...')

# Stream logs for real-time monitoring
process = subprocess.Popen([PYBIN, str(DRIVER_PATH)], stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)
for line in process.stdout:
    print(line, end='')

process.wait()

if process.returncode != 0:
    raise RuntimeError(f'VCD driver failed with code {process.returncode}')

Running VCD Benchmarks on Blackwell GPU...
The cache for model files in Transformers v4.22.0 has been updated. Migrating your old cache. This is a one-time only operation. You can interrupt this and resume the migration later on by calling `transformers.utils.move_cache()`.

0it [00:00, ?it/s]
0it [00:00, ?it/s]
/usr/local/miniconda/envs/vcd310/lib/python3.10/site-packages/huggingface_hub/file_download.py:949: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

Downloading shards:   0%|          | 0/2 [00:00<?, ?it/s]
Downloading shards:  50%|█████     | 1/2 [00:29<00:29, 29.50s/it]
Downloading shards: 100%|██████████| 2/2 [00:44<00:00, 21.26s/it]
Downloading shards: 100%|██████████| 2/2 [00:44<00:00, 22.50s/it]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]
Loading checkpoint shards:  50%|█████     | 1/2 [00:02<00:02,  2.68s/it]
Loading checkpoint shards: 100%|██████████| 2/2 [00:03<00:00,  1.70s/it]
Loading checkpoint shards: 100%|██████████| 2/2 [00:03<00:00,  1.85s/it]

  0%|          | 0/3000 [00:00<?, ?it/s]
  0%|          | 1/3000 [00:00<31:08,  1.61it/s]
  0%|          | 3/3000 [00:00<12:08,  4.11it/s]
  0%|          | 5/3000 [00:01<08:03,  6.19it/s]
  0%|          | 7/3000 [00:01<06:24,  7.78it/s]
  0%|          | 9/3000 [00:01<05:33,  8.97it/s]
  0%|          | 11/3000 [00:01<05:03,  9.86it/s]
  0%|          | 13/3000 [00:01<04:45, 10.45it/s]
  0%|          | 15/3000 [00:01<04:34, 10.86it/s]
  1%|          | 17/3000 [00:02<04:27, 11.14it/s]
  1%|          | 19/3000 [00:02<04:22, 11.36it/s]
  1%|          | 21/3000 [00:02<04:18, 11.53it/s]
  1%|          | 23/3000 [00:02<04:15, 11.65it/s]
  1%|          | 25/3000 [00:02<04:13, 11.75it/s]
  1%|          | 27/3000 [00:02<04:10, 11.87it/s]
  1%|          | 29/3000 [00:03<04:08, 11.97it/s]
  1%|          | 31/3000 [00:03<04:07, 11.97it/s]
  1%|          | 33/3000 [00:03<04:08, 11.95it/s]
  1%|          | 35/3000 [00:03<04:08, 11.92it/s]
  1%|          | 37/3000 [00:03<04:08, 11.93it/s]
  1%|▏         | 39/3000 [00:03<04:08, 11.90it/s]
  1%|▏         | 41/3000 [00:04<04:08, 11.93it/s]
  1%|▏         | 43/3000 [00:04<04:07, 11.94it/s]
  2%|▏         | 45/3000 [00:04<04:07, 11.93it/s]
  2%|▏         | 47/3000 [00:04<04:06, 11.97it/s]
  2%|▏         | 49/3000 [00:04<04:06, 11.98it/s]
  2%|▏         | 51/3000 [00:04<04:06, 11.98it/s]
  2%|▏         | 53/3000 [00:05<04:06, 11.96it/s]
  2%|▏         | 55/3000 [00:05<04:06, 11.96it/s]
  2%|▏         | 57/3000 [00:05<04:06, 11.94it/s]
  2%|▏         | 59/3000 [00:05<04:06, 11.93it/s]
  2%|▏         | 61/3000 [00:05<04:06, 11.93it/s]
  2%|▏         | 63/3000 [00:05<04:05, 11.98it/s]
  2%|▏         | 65/3000 [00:06<04:04, 11.99it/s]
  2%|▏         | 67/3000 [00:06<04:03, 12.03it/s]
  2%|▏         | 69/3000 [00:06<04:01, 12.12it/s]
  2%|▏         | 71/3000 [00:06<04:00, 12.17it/s]
  2%|▏         | 73/3000 [00:06<04:00, 12.17it/s]
  2%|▎         | 75/3000 [00:06<04:01, 12.11it/s]
  3%|▎         | 77/3000 [00:07<04:01, 12.12it/s]
  3%|▎         | 79/3000 [00:07<03:59, 12.18it/s]
  3%|▎         | 81/3000 [00:07<03:58, 12.24it/s]
  3%|▎         | 83/3000 [00:07<03:57, 12.28it/s]
  3%|▎         | 85/3000 [00:07<03:56, 12.33it/s]
  3%|▎         | 87/3000 [00:07<03:55, 12.38it/s]
  3%|▎         | 89/3000 [00:07<03:54, 12.43it/s]
  3%|▎         | 91/3000 [00:08<03:53, 12.44it/s]
  3%|▎         | 93/3000 [00:08<03:53, 12.43it/s]
  3%|▎         | 95/3000 [00:08<03:54, 12.40it/s]
  3%|▎         | 97/3000 [00:08<03:53, 12.41it/s]
  3%|▎         | 99/3000 [00:08<03:53, 12.43it/s]
  3%|▎         | 101/3000 [00:08<03:53, 12.41it/s]
  3%|▎         | 103/3000 [00:09<03:54, 12.37it/s]
  4%|▎         | 105/3000 [00:09<03:54, 12.32it/s]
  4%|▎         | 107/3000 [00:09<03:55, 12.29it/s]
  4%|▎         | 109/3000 [00:09<03:54, 12.34it/s]
  4%|▎         | 111/3000 [00:09<03:53, 12.38it/s]
  4%|▍         | 113/3000 [00:09<03:52, 12.42it/s]
  4%|▍         | 115/3000 [00:10<03:51, 12.46it/s]
  4%|▍         | 117/3000 [00:10<03:50, 12.49it/s]
  4%|▍         | 119/3000 [00:10<03:49, 12.53it/s]
  4%|▍         | 121/3000 [00:10<03:50, 12.50it/s]
  4%|▍         | 123/3000 [00:10<03:51, 12.45it/s]
  4%|▍         | 125/3000 [00:10<03:51, 12.44it/s]
  4%|▍         | 127/3000 [00:11<03:51, 12.42it/s]
  4%|▍         | 129/3000 [00:11<03:51, 12.39it/s]
  4%|▍         | 131/3000 [00:11<03:52, 12.36it/s]
  4%|▍         | 133/3000 [00:11<03:51, 12.37it/s]
  4%|▍         | 135/3000 [00:11<03:50, 12.41it/s]
  5%|▍         | 137/3000 [00:11<03:50, 12.42it/s]
  5%|▍         | 139/3000 [00:12<03:49, 12.48it/s]
  5%|▍         | 141/3000 [00:12<03:48, 12.54it/s]
  5%|▍         | 143/3000 [00:12<03:47, 12.58it/s]
  5%|▍         | 145/3000 [00:12<03:46, 12.58it/s]
  5%|▍         | 147/3000 [00:12<03:47, 12.57it/s]
  5%|▍         | 149/3000 [00:12<03:46, 12.57it/s]
  5%|▌         | 151/3000 [00:12<03:46, 12.57it/s]
  5%|▌         | 153/3000 [00:13<03:45, 12.61it/s]
  5%|▌         | 155/3000 [00:13<03:45, 12.62it/s]
  5%|▌         | 157/3000 [00:13<03:45, 12.60it/s]
  5%|▌         | 159/3000 [00:13<03:46, 12.55it/s]
  5%|▌         | 161/3000 [00:13<03:47, 12.48it/s]
  5%|▌         | 163/3000 [00:13<03:48, 12.43it/s]
  6%|▌         | 165/3000 [00:14<03:48, 12.39it/s]
  6%|▌         | 167/3000 [00:14<03:48, 12.37it/s]
  6%|▌         | 169/3000 [00:14<03:48, 12.41it/s]
  6%|▌         | 171/3000 [00:14<03:47, 12.46it/s]
  6%|▌         | 173/3000 [00:14<03:46, 12.50it/s]
  6%|▌         | 175/3000 [00:14<03:45, 12.51it/s]
  6%|▌         | 177/3000 [00:15<03:45, 12.49it/s]
  6%|▌         | 179/3000 [00:15<03:46, 12.46it/s]
  6%|▌         | 181/3000 [00:15<03:45, 12.48it/s]
  6%|▌         | 183/3000 [00:15<03:45, 12.47it/s]
  6%|▌         | 185/3000 [00:15<03:46, 12.45it/s]
  6%|▌         | 187/3000 [00:15<03:45, 12.48it/s]
  6%|▋         | 189/3000 [00:16<03:44, 12.51it/s]
  6%|▋         | 191/3000 [00:16<03:43, 12.55it/s]
  6%|▋         | 193/3000 [00:16<03:43, 12.58it/s]
  6%|▋         | 195/3000 [00:16<03:42, 12.60it/s]
  7%|▋         | 197/3000 [00:16<03:42, 12.61it/s]
  7%|▋         | 199/3000 [00:16<03:42, 12.56it/s]
  7%|▋         | 201/3000 [00:16<03:43, 12.52it/s]
  7%|▋         | 203/3000 [00:17<03:43, 12.49it/s]
  7%|▋         | 205/3000 [00:17<03:43, 12.51it/s]
  7%|▋         | 207/3000 [00:17<03:42, 12.57it/s]
  7%|▋         | 209/3000 [00:17<03:41, 12.61it/s]
  7%|▋         | 211/3000 [00:17<03:40, 12.63it/s]
  7%|▋         | 213/3000 [00:17<03:40, 12.64it/s]
  7%|▋         | 215/3000 [00:18<03:40, 12.66it/s]
  7%|▋         | 217/3000 [00:18<03:40, 12.63it/s]
  7%|▋         | 219/3000 [00:18<03:41, 12.58it/s]
  7%|▋         | 221/3000 [00:18<03:41, 12.55it/s]
  7%|▋         | 223/3000 [00:18<03:42, 12.50it/s]
  8%|▊         | 225/3000 [00:18<03:42, 12.47it/s]
  8%|▊         | 227/3000 [00:19<03:43, 12.43it/s]
  8%|▊         | 229/3000 [00:19<03:42, 12.44it/s]
  8%|▊         | 231/3000 [00:19<03:42, 12.46it/s]
  8%|▊         | 233/3000 [00:19<03:41, 12.48it/s]
  8%|▊         | 235/3000 [00:19<03:41, 12.49it/s]
  8%|▊         | 237/3000 [00:19<03:41, 12.50it/s]
  8%|▊         | 239/3000 [00:19<03:40, 12.54it/s]
  8%|▊         | 241/3000 [00:20<03:39, 12.55it/s]
  8%|▊         | 243/3000 [00:20<03:39, 12.54it/s]
  8%|▊         | 245/3000 [00:20<03:40, 12.52it/s]
  8%|▊         | 247/3000 [00:20<03:40, 12.47it/s]
  8%|▊         | 249/3000 [00:20<03:41, 12.43it/s]
  8%|▊         | 251/3000 [00:20<03:41, 12.41it/s]
  8%|▊         | 253/3000 [00:21<03:40, 12.46it/s]
  8%|▊         | 255/3000 [00:21<03:39, 12.51it/s]
  9%|▊         | 257/3000 [00:21<03:38, 12.54it/s]
  9%|▊         | 259/3000 [00:21<03:38, 12.54it/s]
  9%|▊         | 261/3000 [00:21<03:38, 12.51it/s]
  9%|▉         | 263/3000 [00:21<03:39, 12.48it/s]
  9%|▉         | 265/3000 [00:22<03:38, 12.50it/s]
  9%|▉         | 267/3000 [00:22<03:37, 12.55it/s]
  9%|▉         | 269/3000 [00:22<03:37, 12.56it/s]
  9%|▉         | 271/3000 [00:22<03:37, 12.53it/s]
  9%|▉         | 273/3000 [00:22<03:38, 12.49it/s]
  9%|▉         | 275/3000 [00:22<03:39, 12.42it/s]
  9%|▉         | 277/3000 [00:23<03:39, 12.41it/s]
  9%|▉         | 279/3000 [00:23<03:38, 12.44it/s]
  9%|▉         | 281/3000 [00:23<03:38, 12.43it/s]
  9%|▉         | 283/3000 [00:23<03:37, 12.46it/s]
 10%|▉         | 285/3000 [00:23<03:36, 12.51it/s]
 10%|▉         | 287/3000 [00:23<03:36, 12.55it/s]
 10%|▉         | 289/3000 [00:23<03:36, 12.54it/s]
 10%|▉         | 291/3000 [00:24<03:36, 12.50it/s]
 10%|▉         | 293/3000 [00:24<03:37, 12.47it/s]
 10%|▉         | 295/3000 [00:24<03:37, 12.41it/s]
 10%|▉         | 297/3000 [00:24<03:39, 12.32it/s]
 10%|▉         | 299/3000 [00:24<03:40, 12.25it/s]
 10%|█         | 301/3000 [00:24<03:40, 12.26it/s]
 10%|█         | 303/3000 [00:25<03:39, 12.30it/s]
 10%|█         | 305/3000 [00:25<03:38, 12.34it/s]
 10%|█         | 307/3000 [00:25<03:38, 12.34it/s]
 10%|█         | 309/3000 [00:25<03:38, 12.32it/s]
 10%|█         | 311/3000 [00:25<03:38, 12.30it/s]
 10%|█         | 313/3000 [00:25<03:38, 12.30it/s]
 10%|█         | 315/3000 [00:26<03:38, 12.31it/s]
 11%|█         | 317/3000 [00:26<03:37, 12.31it/s]
 11%|█         | 319/3000 [00:26<03:37, 12.32it/s]
 11%|█         | 321/3000 [00:26<03:37, 12.34it/s]
 11%|█         | 323/3000 [00:26<03:36, 12.34it/s]
 11%|█         | 325/3000 [00:26<03:36, 12.36it/s]
 11%|█         | 327/3000 [00:27<03:35, 12.38it/s]
 11%|█         | 329/3000 [00:27<03:35, 12.39it/s]
 11%|█         | 331/3000 [00:27<03:35, 12.39it/s]
 11%|█         | 333/3000 [00:27<03:35, 12.39it/s]
 11%|█         | 335/3000 [00:27<03:35, 12.37it/s]
 11%|█         | 337/3000 [00:27<03:35, 12.37it/s]
 11%|█▏        | 339/3000 [00:28<03:34, 12.40it/s]
 11%|█▏        | 341/3000 [00:28<03:33, 12.43it/s]
 11%|█▏        | 343/3000 [00:28<03:34, 12.41it/s]
 12%|█▏        | 345/3000 [00:28<03:33, 12.42it/s]
 12%|█▏        | 347/3000 [00:28<03:33, 12.41it/s]
 12%|█▏        | 349/3000 [00:28<03:34, 12.38it/s]
 12%|█▏        | 351/3000 [00:29<03:35, 12.30it/s]
 12%|█▏        | 353/3000 [00:29<03:35, 12.26it/s]
 12%|█▏        | 355/3000 [00:29<03:35, 12.29it/s]
 12%|█▏        | 357/3000 [00:29<03:34, 12.32it/s]
 12%|█▏        | 359/3000 [00:29<03:34, 12.32it/s]
 12%|█▏        | 361/3000 [00:29<03:33, 12.36it/s]
 12%|█▏        | 363/3000 [00:29<03:33, 12.38it/s]
 12%|█▏        | 365/3000 [00:30<03:31, 12.43it/s]
 12%|█▏        | 367/3000 [00:30<03:31, 12.42it/s]
 12%|█▏        | 369/3000 [00:30<03:32, 12.40it/s]
 12%|█▏        | 371/3000 [00:30<03:31, 12.40it/s]
 12%|█▏        | 373/3000 [00:30<03:32, 12.39it/s]
 12%|█▎        | 375/3000 [00:30<03:31, 12.39it/s]
 13%|█▎        | 377/3000 [00:31<03:32, 12.36it/s]
 13%|█▎        | 379/3000 [00:31<03:31, 12.38it/s]
 13%|█▎        | 381/3000 [00:31<03:31, 12.36it/s]
 13%|█▎        | 383/3000 [00:31<03:31, 12.38it/s]
 13%|█▎        | 385/3000 [00:31<03:31, 12.38it/s]
 13%|█▎        | 387/3000 [00:31<03:31, 12.37it/s]
 13%|█▎        | 389/3000 [00:32<03:31, 12.36it/s]
 13%|█▎        | 391/3000 [00:32<03:30, 12.40it/s]
 13%|█▎        | 393/3000 [00:32<03:29, 12.45it/s]
 13%|█▎        | 395/3000 [00:32<03:28, 12.48it/s]
 13%|█▎        | 397/3000 [00:32<03:28, 12.49it/s]
 13%|█▎        | 399/3000 [00:32<03:27, 12.55it/s]
 13%|█▎        | 401/3000 [00:33<03:26, 12.56it/s]
 13%|█▎        | 403/3000 [00:33<03:26, 12.57it/s]
 14%|█▎        | 405/3000 [00:33<03:26, 12.55it/s]
 14%|█▎        | 407/3000 [00:33<03:27, 12.50it/s]
 14%|█▎        | 409/3000 [00:33<03:27, 12.49it/s]
 14%|█▎        | 411/3000 [00:33<03:27, 12.47it/s]
 14%|█▍        | 413/3000 [00:34<03:27, 12.45it/s]
 14%|█▍        | 415/3000 [00:34<03:27, 12.49it/s]
 14%|█▍        | 417/3000 [00:34<03:25, 12.54it/s]
 14%|█▍        | 419/3000 [00:34<03:25, 12.58it/s]
 14%|█▍        | 421/3000 [00:34<03:24, 12.59it/s]
 14%|█▍        | 423/3000 [00:34<03:24, 12.59it/s]
 14%|█▍        | 425/3000 [00:34<03:24, 12.61it/s]
 14%|█▍        | 427/3000 [00:35<03:24, 12.60it/s]
 14%|█▍        | 429/3000 [00:35<03:24, 12.56it/s]
 14%|█▍        | 431/3000 [00:35<03:24, 12.54it/s]
 14%|█▍        | 433/3000 [00:35<03:25, 12.52it/s]
 14%|█▍        | 435/3000 [00:35<03:24, 12.51it/s]
 15%|█▍        | 437/3000 [00:35<03:24, 12.52it/s]
 15%|█▍        | 439/3000 [00:36<03:24, 12.50it/s]
 15%|█▍        | 441/3000 [00:36<03:25, 12.48it/s]
 15%|█▍        | 443/3000 [00:36<03:25, 12.44it/s]
 15%|█▍        | 445/3000 [00:36<03:25, 12.46it/s]
 15%|█▍        | 447/3000 [00:36<03:24, 12.46it/s]
 15%|█▍        | 449/3000 [00:36<03:24, 12.45it/s]
 15%|█▌        | 451/3000 [00:37<03:24, 12.48it/s]
 15%|█▌        | 453/3000 [00:37<03:23, 12.51it/s]
 15%|█▌        | 455/3000 [00:37<03:23, 12.53it/s]
 15%|█▌        | 457/3000 [00:37<03:23, 12.50it/s]
 15%|█▌        | 459/3000 [00:37<03:23, 12.47it/s]
 15%|█▌        | 461/3000 [00:37<03:23, 12.45it/s]
 15%|█▌        | 463/3000 [00:38<03:23, 12.44it/s]
 16%|█▌        | 465/3000 [00:38<03:24, 12.42it/s]
 16%|█▌        | 467/3000 [00:38<03:24, 12.41it/s]
 16%|█▌        | 469/3000 [00:38<03:23, 12.44it/s]
 16%|█▌        | 471/3000 [00:38<03:22, 12.47it/s]
 16%|█▌        | 473/3000 [00:38<03:22, 12.46it/s]
 16%|█▌        | 475/3000 [00:38<03:22, 12.45it/s]
 16%|█▌        | 477/3000 [00:39<03:22, 12.44it/s]
 16%|█▌        | 479/3000 [00:39<03:23, 12.41it/s]
 16%|█▌        | 481/3000 [00:39<03:22, 12.43it/s]
 16%|█▌        | 483/3000 [00:39<03:22, 12.44it/s]
 16%|█▌        | 485/3000 [00:39<03:22, 12.43it/s]
 16%|█▌        | 487/3000 [00:39<03:22, 12.41it/s]
 16%|█▋        | 489/3000 [00:40<03:23, 12.36it/s]
 16%|█▋        | 491/3000 [00:40<03:23, 12.34it/s]
 16%|█▋        | 493/3000 [00:40<03:23, 12.30it/s]
 16%|█▋        | 495/3000 [00:40<03:23, 12.28it/s]
 17%|█▋        | 497/3000 [00:40<03:23, 12.28it/s]
 17%|█▋        | 499/3000 [00:40<03:23, 12.29it/s]
 17%|█▋        | 501/3000 [00:41<03:22, 12.32it/s]
 17%|█▋        | 503/3000 [00:41<03:22, 12.34it/s]
 17%|█▋        | 505/3000 [00:41<03:21, 12.36it/s]
 17%|█▋        | 507/3000 [00:41<03:21, 12.36it/s]
 17%|█▋        | 509/3000 [00:41<03:21, 12.38it/s]
 17%|█▋        | 511/3000 [00:41<03:21, 12.38it/s]
 17%|█▋        | 513/3000 [00:42<03:20, 12.38it/s]
 17%|█▋        | 515/3000 [00:42<03:20, 12.37it/s]
 17%|█▋        | 517/3000 [00:42<03:20, 12.41it/s]
 17%|█▋        | 519/3000 [00:42<03:18, 12.47it/s]
 17%|█▋        | 521/3000 [00:42<03:17, 12.53it/s]
 17%|█▋        | 523/3000 [00:42<03:17, 12.52it/s]
 18%|█▊        | 525/3000 [00:42<03:18, 12.49it/s]
 18%|█▊        | 527/3000 [00:43<03:18, 12.44it/s]
 18%|█▊        | 529/3000 [00:43<03:18, 12.42it/s]
 18%|█▊        | 531/3000 [00:43<03:19, 12.41it/s]
 18%|█▊        | 533/3000 [00:43<03:19, 12.40it/s]
 18%|█▊        | 535/3000 [00:43<03:18, 12.40it/s]
 18%|█▊        | 537/3000 [00:43<03:18, 12.43it/s]
 18%|█▊        | 539/3000 [00:44<03:17, 12.46it/s]
 18%|█▊        | 541/3000 [00:44<03:17, 12.45it/s]
 18%|█▊        | 543/3000 [00:44<03:17, 12.44it/s]
 18%|█▊        | 545/3000 [00:44<03:17, 12.44it/s]
 18%|█▊        | 547/3000 [00:44<03:17, 12.44it/s]
 18%|█▊        | 549/3000 [00:44<03:16, 12.45it/s]
 18%|█▊        | 551/3000 [00:45<03:16, 12.47it/s]
 18%|█▊        | 553/3000 [00:45<03:16, 12.46it/s]
 18%|█▊        | 555/3000 [00:45<03:16, 12.45it/s]
 19%|█▊        | 557/3000 [00:45<03:16, 12.45it/s]
 19%|█▊        | 559/3000 [00:45<03:16, 12.43it/s]
 19%|█▊        | 561/3000 [00:45<03:16, 12.38it/s]
 19%|█▉        | 563/3000 [00:46<03:17, 12.37it/s]
 19%|█▉        | 565/3000 [00:46<03:16, 12.39it/s]
 19%|█▉        | 567/3000 [00:46<03:15, 12.45it/s]
 19%|█▉        | 569/3000 [00:46<03:14, 12.50it/s]
 19%|█▉        | 571/3000 [00:46<03:13, 12.54it/s]
 19%|█▉        | 573/3000 [00:46<03:13, 12.55it/s]
 19%|█▉        | 575/3000 [00:47<03:13, 12.56it/s]
 19%|█▉        | 577/3000 [00:47<03:13, 12.54it/s]
 19%|█▉        | 579/3000 [00:47<03:13, 12.52it/s]
 19%|█▉        | 581/3000 [00:47<03:13, 12.50it/s]
 19%|█▉        | 583/3000 [00:47<03:12, 12.54it/s]
 20%|█▉        | 585/3000 [00:47<03:12, 12.57it/s]
 20%|█▉        | 587/3000 [00:47<03:11, 12.59it/s]
 20%|█▉        | 589/3000 [00:48<03:11, 12.56it/s]
 20%|█▉        | 591/3000 [00:48<03:12, 12.49it/s]
 20%|█▉        | 593/3000 [00:48<03:13, 12.47it/s]
 20%|█▉        | 595/3000 [00:48<03:13, 12.44it/s]
 20%|█▉        | 597/3000 [00:48<03:12, 12.46it/s]
 20%|█▉        | 599/3000 [00:48<03:13, 12.44it/s]
 20%|██        | 601/3000 [00:49<03:12, 12.45it/s]
 20%|██        | 603/3000 [00:49<03:12, 12.44it/s]
 20%|██        | 605/3000 [00:49<03:12, 12.45it/s]
 20%|██        | 607/3000 [00:49<03:12, 12.42it/s]
 20%|██        | 609/3000 [00:49<03:13, 12.38it/s]
 20%|██        | 611/3000 [00:49<03:13, 12.37it/s]
 20%|██        | 613/3000 [00:50<03:12, 12.39it/s]
 20%|██        | 615/3000 [00:50<03:12, 12.39it/s]
 21%|██        | 617/3000 [00:50<03:12, 12.41it/s]
 21%|██        | 619/3000 [00:50<03:11, 12.42it/s]
 21%|██        | 621/3000 [00:50<03:10, 12.46it/s]
 21%|██        | 623/3000 [00:50<03:10, 12.48it/s]
 21%|██        | 625/3000 [00:51<03:10, 12.48it/s]
 21%|██        | 627/3000 [00:51<03:10, 12.47it/s]
 21%|██        | 629/3000 [00:51<03:09, 12.49it/s]
 21%|██        | 631/3000 [00:51<03:09, 12.48it/s]
 21%|██        | 633/3000 [00:51<03:09, 12.51it/s]
 21%|██        | 635/3000 [00:51<03:09, 12.51it/s]
 21%|██        | 637/3000 [00:51<03:09, 12.49it/s]
 21%|██▏       | 639/3000 [00:52<03:09, 12.47it/s]
 21%|██▏       | 641/3000 [00:52<03:09, 12.46it/s]
 21%|██▏       | 643/3000 [00:52<03:09, 12.43it/s]
 22%|██▏       | 645/3000 [00:52<03:09, 12.42it/s]
 22%|██▏       | 647/3000 [00:52<03:09, 12.41it/s]
 22%|██▏       | 649/3000 [00:52<03:09, 12.39it/s]
 22%|██▏       | 651/3000 [00:53<03:09, 12.41it/s]
 22%|██▏       | 653/3000 [00:53<03:09, 12.42it/s]
 22%|██▏       | 655/3000 [00:53<03:08, 12.44it/s]
 22%|██▏       | 657/3000 [00:53<03:07, 12.50it/s]
 22%|██▏       | 659/3000 [00:53<03:07, 12.51it/s]
 22%|██▏       | 661/3000 [00:53<03:06, 12.52it/s]
 22%|██▏       | 663/3000 [00:54<03:07, 12.48it/s]
 22%|██▏       | 665/3000 [00:54<03:07, 12.47it/s]
 22%|██▏       | 667/3000 [00:54<03:07, 12.46it/s]
 22%|██▏       | 669/3000 [00:54<03:07, 12.45it/s]
 22%|██▏       | 671/3000 [00:54<03:07, 12.43it/s]
 22%|██▏       | 673/3000 [00:54<03:07, 12.42it/s]
 22%|██▎       | 675/3000 [00:55<03:07, 12.41it/s]
 23%|██▎       | 677/3000 [00:55<03:06, 12.43it/s]
 23%|██▎       | 679/3000 [00:55<03:07, 12.37it/s]
 23%|██▎       | 681/3000 [00:55<03:08, 12.33it/s]
 23%|██▎       | 683/3000 [00:55<03:08, 12.30it/s]
 23%|██▎       | 685/3000 [00:55<03:08, 12.29it/s]
 23%|██▎       | 687/3000 [00:56<03:07, 12.33it/s]
 23%|██▎       | 689/3000 [00:56<03:07, 12.33it/s]
 23%|██▎       | 691/3000 [00:56<03:06, 12.37it/s]
 23%|██▎       | 693/3000 [00:56<03:06, 12.39it/s]
 23%|██▎       | 695/3000 [00:56<03:05, 12.41it/s]
 23%|██▎       | 697/3000 [00:56<03:05, 12.41it/s]
 23%|██▎       | 699/3000 [00:56<03:05, 12.39it/s]
 23%|██▎       | 701/3000 [00:57<03:05, 12.40it/s]
 23%|██▎       | 703/3000 [00:57<03:05, 12.39it/s]
 24%|██▎       | 705/3000 [00:57<03:05, 12.38it/s]
 24%|██▎       | 707/3000 [00:57<03:04, 12.42it/s]
 24%|██▎       | 709/3000 [00:57<03:04, 12.41it/s]
 24%|██▎       | 711/3000 [00:57<03:04, 12.40it/s]
 24%|██▍       | 713/3000 [00:58<03:04, 12.41it/s]
 24%|██▍       | 715/3000 [00:58<03:04, 12.39it/s]
 24%|██▍       | 717/3000 [00:58<03:04, 12.39it/s]
 24%|██▍       | 719/3000 [00:58<03:03, 12.41it/s]
 24%|██▍       | 721/3000 [00:58<03:03, 12.39it/s]
 24%|██▍       | 723/3000 [00:58<03:03, 12.38it/s]
 24%|██▍       | 725/3000 [00:59<03:04, 12.36it/s]
 24%|██▍       | 727/3000 [00:59<03:03, 12.37it/s]
 24%|██▍       | 729/3000 [00:59<03:03, 12.40it/s]
 24%|██▍       | 731/3000 [00:59<03:02, 12.42it/s]
 24%|██▍       | 733/3000 [00:59<03:02, 12.43it/s]
 24%|██▍       | 735/3000 [00:59<03:02, 12.42it/s]
 25%|██▍       | 737/3000 [01:00<03:02, 12.42it/s]

In [11]:
import json
import re
import pandas as pd
from pathlib import Path
from IPython.display import display, Markdown

# --- Config ---
P1 = '/content/VCD_project/myTasks'
SEED = 55
out_dir = Path(f'{P1}/output')

def parse_metrics_txt(path: Path):
    if not path.exists(): return None
    text = path.read_text()
    def g(name):
        m = re.search(rf"^{name}:\s*([0-9.]+)", text, re.MULTILINE)
        return float(m.group(1)) if m else float('nan')
    return {'Accuracy': g('Accuracy'), 'Precision': g('Precision'), 'Recall': g('Recall'), 'F1': g('F1')}

def parse_metrics_json(path: Path):
    if not path.exists(): return None
    data = json.loads(path.read_text())
    return {
        'Accuracy': float(data.get('accuracy', float('nan'))),
        'Precision': float(data.get('precision', float('nan'))),
        'Recall': float(data.get('recall', float('nan'))),
        'F1': float(data.get('f1', float('nan')))
    }

# --- Data Collection ---
results = []
configs = [
    ('random', 'VCD', out_dir / f'metrics_random_vcd_seed{SEED}.txt', parse_metrics_txt),
    ('random', 'MFCD', out_dir / 'mfcd_random.json', parse_metrics_json),
    ('popular', 'VCD', out_dir / f'metrics_popular_vcd_seed{SEED}.txt', parse_metrics_txt),
    ('popular', 'MFCD', out_dir / 'mfcd_popular.json', parse_metrics_json),
]

for split, method, path, parser in configs:
    metrics = parser(path)
    if metrics:
        row = {'Split': split, 'Method': method}
        row.update(metrics)
        results.append(row)

# --- Display Logic ---
if results:
    df = pd.DataFrame(results)
    
    # Apply styling: 4 decimal places and highlight the best F1 per split
    styled_df = df.style.format({
        'Accuracy': '{:.4f}', 
        'Precision': '{:.4f}', 
        'Recall': '{:.4f}', 
        'F1': '{:.4f}'
    }).hide(axis='index')
    
    display(Markdown(f"### 🚀 Blackwell GPU Benchmark Results (Seed: {SEED})"))
    display(styled_df)
else:
    print("⚠️ No result files found in output directory. Check if the drivers finished running.")

### 🚀 Blackwell GPU Benchmark Results (Seed: 55)

# Experimental stuff

In [14]:
import subprocess
from pathlib import Path

PYBIN_PATH = '/tmp/mytasks_python_bin.txt'
PYBIN = Path(PYBIN_PATH).read_text().strip()
DRIVER_PATH = Path('/tmp/vcd_driver.py')

vcd_driver = """
import os
import sys
import torch
import gc
import subprocess
from pathlib import Path

ROOT = '/content/VCD_project'
ORIG = f'{ROOT}/originalProject'
EXP_DIR = f'{ORIG}/experiments'
OUT_DIR = f'{ROOT}/myTasks/output'
COCO_VAL = '/content/datasets/coco/val2014'
MODEL_PATH = 'liuhaotian/llava-v1.5-7b'
SEED = '55'

os.makedirs(OUT_DIR, exist_ok=True)

def run_vqa_step(split, method):
    question_file = f"{EXP_DIR}/data/POPE/coco/coco_pope_{split}.json"
    answers_file = f"{OUT_DIR}/llava15_coco_pope_{split}_answers_{method}_seed{SEED}.jsonl"
    metrics_file = f"{OUT_DIR}/metrics_{split}_{method}_seed{SEED}.txt"

    print(f"\\n>>> STARTING: Split={split} | Method={method}")

    cmd = [
        sys.executable, "./eval/object_hallucination_vqa_llava.py",
        "--model-path", MODEL_PATH,
        "--question-file", question_file,
        "--image-folder", COCO_VAL,
        "--answers-file", answers_file,
        "--seed", SEED
    ]

    if method == "vcd":
        cmd += ["--use_cd", "--cd_alpha", "1.0", "--cd_beta", "0.2", "--noise_step", "500"]

    os.chdir(EXP_DIR)
    subprocess.run(cmd, check=True)

    eval_cmd = [sys.executable, "./eval/eval_pope.py", "--gt_files", question_file, "--gen_files", answers_file]
    with open(metrics_file, "w") as f:
        subprocess.run(eval_cmd, stdout=f, check=True)
    
    gc.collect()
    torch.cuda.empty_cache()

# This loop ensures both 'regular' and 'vcd' are produced
for split in ['random', 'popular']:
    for method in ['regular', 'vcd']:
        run_vqa_step(split, method)
"""

DRIVER_PATH.write_text(vcd_driver)
process = subprocess.Popen([PYBIN, str(DRIVER_PATH)], stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)
for line in process.stdout:
    print(line, end='')
process.wait()

/usr/local/miniconda/envs/vcd310/lib/python3.10/site-packages/huggingface_hub/file_download.py:949: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]
Loading checkpoint shards:  50%|█████     | 1/2 [00:02<00:02,  2.68s/it]
Loading checkpoint shards: 100%|██████████| 2/2 [00:03<00:00,  1.70s/it]
Loading checkpoint shards: 100%|██████████| 2/2 [00:03<00:00,  1.84s/it]

  0%|          | 0/3000 [00:00<?, ?it/s]
  0%|          | 1/3000 [00:00<17:06,  2.92it/s]
  0%|          | 3/3000 [00:00<07:34,  6.60it/s]
  0%|          | 5/3000 [00:00<05:50,  8.55it/s]
  0%|          | 7/3000 [00:00<05:08,  9.71it/s]
  0%|          | 9/3000 [00:01<04:45, 10.48it/s]
  0%|          | 11/3000 [00:01<04:32, 10.98it/s]
  0%|          | 13/3000 [00:01<04:24, 11.28it/s]
  0%|          | 15/3000 [00:01<04:20, 11.45it/s]
  1%|          | 17/3000 [00:01<04:17, 11.56it/s]
  1%|          | 19/3000 [00:01<04:15, 11.66it/s]
  1%|          | 21/3000 [00:02<04:13, 11.74it/s]
  1%|          | 23/3000 [00:02<04:12, 11.80it/s]
  1%|          | 25/3000 [00:02<04:10, 11.86it/s]
  1%|          | 27/3000 [00:02<04:08, 11.95it/s]
  1%|          | 29/3000 [00:02<04:07, 12.01it/s]
  1%|          | 31/3000 [00:02<04:07, 12.01it/s]
  1%|          | 33/3000 [00:03<04:07, 11.97it/s]
  1%|          | 35/3000 [00:03<04:08, 11.95it/s]
  1%|          | 37/3000 [00:03<04:07, 11.96it/s]
  1%|▏         | 39/3000 [00:03<04:08, 11.93it/s]
  1%|▏         | 41/3000 [00:03<04:07, 11.95it/s]
  1%|▏         | 43/3000 [00:03<04:07, 11.94it/s]
  2%|▏         | 45/3000 [00:04<04:07, 11.92it/s]
  2%|▏         | 47/3000 [00:04<04:07, 11.93it/s]
  2%|▏         | 49/3000 [00:04<04:07, 11.91it/s]
  2%|▏         | 51/3000 [00:04<04:07, 11.91it/s]
  2%|▏         | 53/3000 [00:04<04:08, 11.87it/s]
  2%|▏         | 55/3000 [00:04<04:07, 11.91it/s]
  2%|▏         | 57/3000 [00:05<04:07, 11.90it/s]
  2%|▏         | 59/3000 [00:05<04:07, 11.90it/s]
  2%|▏         | 61/3000 [00:05<04:06, 11.91it/s]
  2%|▏         | 63/3000 [00:05<04:05, 11.96it/s]
  2%|▏         | 65/3000 [00:05<04:05, 11.97it/s]
  2%|▏         | 67/3000 [00:05<04:04, 11.99it/s]
  2%|▏         | 69/3000 [00:06<04:03, 12.04it/s]
  2%|▏         | 71/3000 [00:06<04:02, 12.07it/s]
  2%|▏         | 73/3000 [00:06<04:01, 12.10it/s]
  2%|▎         | 75/3000 [00:06<04:02, 12.08it/s]
  3%|▎         | 77/3000 [00:06<04:02, 12.07it/s]
  3%|▎         | 79/3000 [00:06<04:01, 12.12it/s]
  3%|▎         | 81/3000 [00:07<03:59, 12.20it/s]
  3%|▎         | 83/3000 [00:07<03:57, 12.27it/s]
  3%|▎         | 85/3000 [00:07<03:56, 12.32it/s]
  3%|▎         | 87/3000 [00:07<03:56, 12.34it/s]
  3%|▎         | 89/3000 [00:07<03:56, 12.31it/s]
  3%|▎         | 91/3000 [00:07<03:57, 12.25it/s]
  3%|▎         | 93/3000 [00:07<03:57, 12.26it/s]
  3%|▎         | 95/3000 [00:08<03:57, 12.23it/s]
  3%|▎         | 97/3000 [00:08<03:56, 12.26it/s]
  3%|▎         | 99/3000 [00:08<03:56, 12.28it/s]
  3%|▎         | 101/3000 [00:08<03:56, 12.28it/s]
  3%|▎         | 103/3000 [00:08<03:55, 12.33it/s]
  4%|▎         | 105/3000 [00:08<03:54, 12.33it/s]
  4%|▎         | 107/3000 [00:09<03:54, 12.33it/s]
  4%|▎         | 109/3000 [00:09<03:54, 12.32it/s]
  4%|▎         | 111/3000 [00:09<03:54, 12.32it/s]
  4%|▍         | 113/3000 [00:09<03:54, 12.34it/s]
  4%|▍         | 115/3000 [00:09<03:53, 12.36it/s]
  4%|▍         | 117/3000 [00:09<03:52, 12.38it/s]
  4%|▍         | 119/3000 [00:10<03:52, 12.41it/s]
  4%|▍         | 121/3000 [00:10<03:52, 12.40it/s]
  4%|▍         | 123/3000 [00:10<03:52, 12.38it/s]
  4%|▍         | 125/3000 [00:10<03:51, 12.39it/s]
  4%|▍         | 127/3000 [00:10<03:52, 12.38it/s]
  4%|▍         | 129/3000 [00:10<03:52, 12.36it/s]
  4%|▍         | 131/3000 [00:11<03:52, 12.35it/s]
  4%|▍         | 133/3000 [00:11<03:51, 12.36it/s]
  4%|▍         | 135/3000 [00:11<03:51, 12.40it/s]
  5%|▍         | 137/3000 [00:11<03:50, 12.40it/s]
  5%|▍         | 139/3000 [00:11<03:49, 12.47it/s]
  5%|▍         | 141/3000 [00:11<03:48, 12.53it/s]
  5%|▍         | 143/3000 [00:12<03:47, 12.58it/s]
  5%|▍         | 145/3000 [00:12<03:46, 12.59it/s]
  5%|▍         | 147/3000 [00:12<03:47, 12.57it/s]
  5%|▍         | 149/3000 [00:12<03:46, 12.57it/s]
  5%|▌         | 151/3000 [00:12<03:46, 12.57it/s]
  5%|▌         | 153/3000 [00:12<03:45, 12.61it/s]
  5%|▌         | 155/3000 [00:12<03:45, 12.61it/s]
  5%|▌         | 157/3000 [00:13<03:45, 12.59it/s]
  5%|▌         | 159/3000 [00:13<03:46, 12.55it/s]
  5%|▌         | 161/3000 [00:13<03:47, 12.48it/s]
  5%|▌         | 163/3000 [00:13<03:47, 12.45it/s]
  6%|▌         | 165/3000 [00:13<03:48, 12.41it/s]
  6%|▌         | 167/3000 [00:13<03:48, 12.40it/s]
  6%|▌         | 169/3000 [00:14<03:47, 12.44it/s]
  6%|▌         | 171/3000 [00:14<03:46, 12.49it/s]
  6%|▌         | 173/3000 [00:14<03:45, 12.53it/s]
  6%|▌         | 175/3000 [00:14<03:45, 12.53it/s]
  6%|▌         | 177/3000 [00:14<03:45, 12.51it/s]
  6%|▌         | 179/3000 [00:14<03:46, 12.48it/s]
  6%|▌         | 181/3000 [00:15<03:45, 12.48it/s]
  6%|▌         | 183/3000 [00:15<03:45, 12.48it/s]
  6%|▌         | 185/3000 [00:15<03:45, 12.46it/s]
  6%|▌         | 187/3000 [00:15<03:45, 12.49it/s]
  6%|▋         | 189/3000 [00:15<03:44, 12.52it/s]
  6%|▋         | 191/3000 [00:15<03:43, 12.56it/s]
  6%|▋         | 193/3000 [00:16<03:42, 12.59it/s]
  6%|▋         | 195/3000 [00:16<03:42, 12.61it/s]
  7%|▋         | 197/3000 [00:16<03:42, 12.62it/s]
  7%|▋         | 199/3000 [00:16<03:42, 12.58it/s]
  7%|▋         | 201/3000 [00:16<03:43, 12.54it/s]
  7%|▋         | 203/3000 [00:16<03:43, 12.50it/s]
  7%|▋         | 205/3000 [00:16<03:43, 12.52it/s]
  7%|▋         | 207/3000 [00:17<03:42, 12.58it/s]
  7%|▋         | 209/3000 [00:17<03:41, 12.62it/s]
  7%|▋         | 211/3000 [00:17<03:40, 12.64it/s]
  7%|▋         | 213/3000 [00:17<03:40, 12.65it/s]
  7%|▋         | 215/3000 [00:17<03:39, 12.67it/s]
  7%|▋         | 217/3000 [00:17<03:40, 12.63it/s]
  7%|▋         | 219/3000 [00:18<03:41, 12.57it/s]
  7%|▋         | 221/3000 [00:18<03:41, 12.54it/s]
  7%|▋         | 223/3000 [00:18<03:42, 12.49it/s]
  8%|▊         | 225/3000 [00:18<03:42, 12.46it/s]
  8%|▊         | 227/3000 [00:18<03:43, 12.42it/s]
  8%|▊         | 229/3000 [00:18<03:42, 12.43it/s]
  8%|▊         | 231/3000 [00:19<03:42, 12.46it/s]
  8%|▊         | 233/3000 [00:19<03:41, 12.48it/s]
  8%|▊         | 235/3000 [00:19<03:41, 12.50it/s]
  8%|▊         | 237/3000 [00:19<03:41, 12.50it/s]
  8%|▊         | 239/3000 [00:19<03:40, 12.54it/s]
  8%|▊         | 241/3000 [00:19<03:39, 12.55it/s]
  8%|▊         | 243/3000 [00:20<03:39, 12.54it/s]
  8%|▊         | 245/3000 [00:20<03:39, 12.52it/s]
  8%|▊         | 247/3000 [00:20<03:40, 12.48it/s]
  8%|▊         | 249/3000 [00:20<03:41, 12.43it/s]
  8%|▊         | 251/3000 [00:20<03:41, 12.42it/s]
  8%|▊         | 253/3000 [00:20<03:40, 12.46it/s]
  8%|▊         | 255/3000 [00:20<03:39, 12.50it/s]
  9%|▊         | 257/3000 [00:21<03:38, 12.54it/s]
  9%|▊         | 259/3000 [00:21<03:38, 12.54it/s]
  9%|▊         | 261/3000 [00:21<03:38, 12.51it/s]
  9%|▉         | 263/3000 [00:21<03:39, 12.49it/s]
  9%|▉         | 265/3000 [00:21<03:38, 12.51it/s]
  9%|▉         | 267/3000 [00:21<03:37, 12.55it/s]
  9%|▉         | 269/3000 [00:22<03:37, 12.56it/s]
  9%|▉         | 271/3000 [00:22<03:37, 12.53it/s]
  9%|▉         | 273/3000 [00:22<03:38, 12.49it/s]
  9%|▉         | 275/3000 [00:22<03:39, 12.43it/s]
  9%|▉         | 277/3000 [00:22<03:39, 12.40it/s]
  9%|▉         | 279/3000 [00:22<03:38, 12.44it/s]
  9%|▉         | 281/3000 [00:23<03:38, 12.44it/s]
  9%|▉         | 283/3000 [00:23<03:37, 12.48it/s]
 10%|▉         | 285/3000 [00:23<03:36, 12.53it/s]
 10%|▉         | 287/3000 [00:23<03:36, 12.56it/s]
 10%|▉         | 289/3000 [00:23<03:36, 12.55it/s]
 10%|▉         | 291/3000 [00:23<03:36, 12.50it/s]
 10%|▉         | 293/3000 [00:24<03:36, 12.48it/s]
 10%|▉         | 295/3000 [00:24<03:37, 12.43it/s]
 10%|▉         | 297/3000 [00:24<03:38, 12.38it/s]
 10%|▉         | 299/3000 [00:24<03:38, 12.35it/s]
 10%|█         | 301/3000 [00:24<03:38, 12.35it/s]
 10%|█         | 303/3000 [00:24<03:37, 12.37it/s]
 10%|█         | 305/3000 [00:24<03:37, 12.39it/s]
 10%|█         | 307/3000 [00:25<03:37, 12.37it/s]
 10%|█         | 309/3000 [00:25<03:38, 12.34it/s]
 10%|█         | 311/3000 [00:25<03:38, 12.32it/s]
 10%|█         | 313/3000 [00:25<03:38, 12.32it/s]
 10%|█         | 315/3000 [00:25<03:37, 12.32it/s]
 11%|█         | 317/3000 [00:25<03:37, 12.32it/s]
 11%|█         | 319/3000 [00:26<03:37, 12.33it/s]
 11%|█         | 321/3000 [00:26<03:36, 12.35it/s]
 11%|█         | 323/3000 [00:26<03:36, 12.34it/s]
 11%|█         | 325/3000 [00:26<03:36, 12.36it/s]
 11%|█         | 327/3000 [00:26<03:35, 12.38it/s]
 11%|█         | 329/3000 [00:26<03:35, 12.39it/s]
 11%|█         | 331/3000 [00:27<03:35, 12.39it/s]
 11%|█         | 333/3000 [00:27<03:35, 12.39it/s]
 11%|█         | 335/3000 [00:27<03:35, 12.37it/s]
 11%|█         | 337/3000 [00:27<03:35, 12.37it/s]
 11%|█▏        | 339/3000 [00:27<03:34, 12.41it/s]
 11%|█▏        | 341/3000 [00:27<03:33, 12.44it/s]
 11%|█▏        | 343/3000 [00:28<03:33, 12.42it/s]
 12%|█▏        | 345/3000 [00:28<03:33, 12.43it/s]
 12%|█▏        | 347/3000 [00:28<03:33, 12.42it/s]
 12%|█▏        | 349/3000 [00:28<03:34, 12.38it/s]
 12%|█▏        | 351/3000 [00:28<03:35, 12.30it/s]
 12%|█▏        | 353/3000 [00:28<03:35, 12.25it/s]
 12%|█▏        | 355/3000 [00:29<03:35, 12.27it/s]
 12%|█▏        | 357/3000 [00:29<03:34, 12.30it/s]
 12%|█▏        | 359/3000 [00:29<03:34, 12.31it/s]
 12%|█▏        | 361/3000 [00:29<03:33, 12.35it/s]
 12%|█▏        | 363/3000 [00:29<03:33, 12.38it/s]
 12%|█▏        | 365/3000 [00:29<03:31, 12.43it/s]
 12%|█▏        | 367/3000 [00:29<03:31, 12.43it/s]
 12%|█▏        | 369/3000 [00:30<03:32, 12.40it/s]
 12%|█▏        | 371/3000 [00:30<03:31, 12.40it/s]
 12%|█▏        | 373/3000 [00:30<03:32, 12.39it/s]
 12%|█▎        | 375/3000 [00:30<03:31, 12.39it/s]
 13%|█▎        | 377/3000 [00:30<03:32, 12.36it/s]
 13%|█▎        | 379/3000 [00:30<03:31, 12.38it/s]
 13%|█▎        | 381/3000 [00:31<03:31, 12.36it/s]
 13%|█▎        | 383/3000 [00:31<03:31, 12.38it/s]
 13%|█▎        | 385/3000 [00:31<03:31, 12.38it/s]
 13%|█▎        | 387/3000 [00:31<03:31, 12.37it/s]
 13%|█▎        | 389/3000 [00:31<03:31, 12.35it/s]
 13%|█▎        | 391/3000 [00:31<03:30, 12.40it/s]
 13%|█▎        | 393/3000 [00:32<03:29, 12.45it/s]
 13%|█▎        | 395/3000 [00:32<03:28, 12.48it/s]
 13%|█▎        | 397/3000 [00:32<03:28, 12.49it/s]
 13%|█▎        | 399/3000 [00:32<03:27, 12.55it/s]
 13%|█▎        | 401/3000 [00:32<03:27, 12.55it/s]
 13%|█▎        | 403/3000 [00:32<03:26, 12.56it/s]
 14%|█▎        | 405/3000 [00:33<03:26, 12.54it/s]
 14%|█▎        | 407/3000 [00:33<03:27, 12.49it/s]
 14%|█▎        | 409/3000 [00:33<03:27, 12.49it/s]
 14%|█▎        | 411/3000 [00:33<03:27, 12.47it/s]
 14%|█▍        | 413/3000 [00:33<03:27, 12.45it/s]
 14%|█▍        | 415/3000 [00:33<03:27, 12.48it/s]
 14%|█▍        | 417/3000 [00:34<03:25, 12.54it/s]
 14%|█▍        | 419/3000 [00:34<03:25, 12.59it/s]
 14%|█▍        | 421/3000 [00:34<03:24, 12.60it/s]
 14%|█▍        | 423/3000 [00:34<03:24, 12.60it/s]
 14%|█▍        | 425/3000 [00:34<03:24, 12.61it/s]
 14%|█▍        | 427/3000 [00:34<03:24, 12.61it/s]
 14%|█▍        | 429/3000 [00:34<03:24, 12.57it/s]
 14%|█▍        | 431/3000 [00:35<03:24, 12.55it/s]
 14%|█▍        | 433/3000 [00:35<03:24, 12.53it/s]
 14%|█▍        | 435/3000 [00:35<03:24, 12.52it/s]
 15%|█▍        | 437/3000 [00:35<03:24, 12.53it/s]
 15%|█▍        | 439/3000 [00:35<03:24, 12.51it/s]
 15%|█▍        | 441/3000 [00:35<03:25, 12.48it/s]
 15%|█▍        | 443/3000 [00:36<03:25, 12.44it/s]
 15%|█▍        | 445/3000 [00:36<03:25, 12.45it/s]
 15%|█▍        | 447/3000 [00:36<03:24, 12.46it/s]
 15%|█▍        | 449/3000 [00:36<03:24, 12.45it/s]
 15%|█▌        | 451/3000 [00:36<03:24, 12.48it/s]
 15%|█▌        | 453/3000 [00:36<03:23, 12.51it/s]
 15%|█▌        | 455/3000 [00:37<03:23, 12.52it/s]
 15%|█▌        | 457/3000 [00:37<03:23, 12.49it/s]
 15%|█▌        | 459/3000 [00:37<03:23, 12.46it/s]
 15%|█▌        | 461/3000 [00:37<03:24, 12.44it/s]
 15%|█▌        | 463/3000 [00:37<03:24, 12.43it/s]
 16%|█▌        | 465/3000 [00:37<03:24, 12.40it/s]
 16%|█▌        | 467/3000 [00:38<03:24, 12.40it/s]
 16%|█▌        | 469/3000 [00:38<03:23, 12.42it/s]
 16%|█▌        | 471/3000 [00:38<03:22, 12.46it/s]
 16%|█▌        | 473/3000 [00:38<03:22, 12.46it/s]
 16%|█▌        | 475/3000 [00:38<03:22, 12.45it/s]
 16%|█▌        | 477/3000 [00:38<03:22, 12.44it/s]
 16%|█▌        | 479/3000 [00:38<03:23, 12.42it/s]
 16%|█▌        | 481/3000 [00:39<03:22, 12.41it/s]
 16%|█▌        | 483/3000 [00:39<03:22, 12.41it/s]
 16%|█▌        | 485/3000 [00:39<03:22, 12.39it/s]
 16%|█▌        | 487/3000 [00:39<03:23, 12.36it/s]
 16%|█▋        | 489/3000 [00:39<03:23, 12.33it/s]
 16%|█▋        | 491/3000 [00:39<03:23, 12.30it/s]
 16%|█▋        | 493/3000 [00:40<03:24, 12.28it/s]
 16%|█▋        | 495/3000 [00:40<03:23, 12.28it/s]
 17%|█▋        | 497/3000 [00:40<03:23, 12.28it/s]
 17%|█▋        | 499/3000 [00:40<03:23, 12.30it/s]
 17%|█▋        | 501/3000 [00:40<03:22, 12.32it/s]
 17%|█▋        | 503/3000 [00:40<03:22, 12.34it/s]
 17%|█▋        | 505/3000 [00:41<03:21, 12.36it/s]
 17%|█▋        | 507/3000 [00:41<03:21, 12.36it/s]
 17%|█▋        | 509/3000 [00:41<03:21, 12.38it/s]
 17%|█▋        | 511/3000 [00:41<03:20, 12.38it/s]
 17%|█▋        | 513/3000 [00:41<03:20, 12.38it/s]
 17%|█▋        | 515/3000 [00:41<03:20, 12.38it/s]
 17%|█▋        | 517/3000 [00:42<03:20, 12.41it/s]
 17%|█▋        | 519/3000 [00:42<03:18, 12.47it/s]
 17%|█▋        | 521/3000 [00:42<03:17, 12.53it/s]
 17%|█▋        | 523/3000 [00:42<03:17, 12.52it/s]
 18%|█▊        | 525/3000 [00:42<03:18, 12.48it/s]
 18%|█▊        | 527/3000 [00:42<03:19, 12.42it/s]
 18%|█▊        | 529/3000 [00:43<03:19, 12.40it/s]
 18%|█▊        | 531/3000 [00:43<03:19, 12.39it/s]
 18%|█▊        | 533/3000 [00:43<03:19, 12.38it/s]
 18%|█▊        | 535/3000 [00:43<03:18, 12.39it/s]
 18%|█▊        | 537/3000 [00:43<03:18, 12.43it/s]
 18%|█▊        | 539/3000 [00:43<03:17, 12.46it/s]
 18%|█▊        | 541/3000 [00:43<03:17, 12.45it/s]
 18%|█▊        | 543/3000 [00:44<03:17, 12.45it/s]
 18%|█▊        | 545/3000 [00:44<03:17, 12.44it/s]
 18%|█▊        | 547/3000 [00:44<03:17, 12.44it/s]
 18%|█▊        | 549/3000 [00:44<03:16, 12.45it/s]
 18%|█▊        | 551/3000 [00:44<03:16, 12.48it/s]
 18%|█▊        | 553/3000 [00:44<03:16, 12.47it/s]
 18%|█▊        | 555/3000 [00:45<03:16, 12.45it/s]
 19%|█▊        | 557/3000 [00:45<03:16, 12.45it/s]
 19%|█▊        | 559/3000 [00:45<03:16, 12.44it/s]
 19%|█▊        | 561/3000 [00:45<03:16, 12.40it/s]
 19%|█▉        | 563/3000 [00:45<03:16, 12.39it/s]
 19%|█▉        | 565/3000 [00:45<03:16, 12.41it/s]
 19%|█▉        | 567/3000 [00:46<03:15, 12.48it/s]
 19%|█▉        | 569/3000 [00:46<03:14, 12.52it/s]
 19%|█▉        | 571/3000 [00:46<03:13, 12.56it/s]
 19%|█▉        | 573/3000 [00:46<03:13, 12.57it/s]
 19%|█▉        | 575/3000 [00:46<03:12, 12.57it/s]
 19%|█▉        | 577/3000 [00:46<03:12, 12.56it/s]
 19%|█▉        | 579/3000 [00:47<03:13, 12.53it/s]
 19%|█▉        | 581/3000 [00:47<03:13, 12.52it/s]
 19%|█▉        | 583/3000 [00:47<03:12, 12.55it/s]
 20%|█▉        | 585/3000 [00:47<03:11, 12.58it/s]
 20%|█▉        | 587/3000 [00:47<03:11, 12.61it/s]
 20%|█▉        | 589/3000 [00:47<03:11, 12.58it/s]
 20%|█▉        | 591/3000 [00:47<03:12, 12.51it/s]
 20%|█▉        | 593/3000 [00:48<03:12, 12.48it/s]
 20%|█▉        | 595/3000 [00:48<03:13, 12.45it/s]
 20%|█▉        | 597/3000 [00:48<03:12, 12.47it/s]
 20%|█▉        | 599/3000 [00:48<03:12, 12.44it/s]
 20%|██        | 601/3000 [00:48<03:12, 12.46it/s]
 20%|██        | 603/3000 [00:48<03:12, 12.45it/s]
 20%|██        | 605/3000 [00:49<03:12, 12.45it/s]
 20%|██        | 607/3000 [00:49<03:12, 12.42it/s]
 20%|██        | 609/3000 [00:49<03:13, 12.39it/s]
 20%|██        | 611/3000 [00:49<03:13, 12.37it/s]
 20%|██        | 613/3000 [00:49<03:12, 12.38it/s]
 20%|██        | 615/3000 [00:49<03:12, 12.38it/s]
 21%|██        | 617/3000 [00:50<03:12, 12.40it/s]
 21%|██        | 619/3000 [00:50<03:11, 12.42it/s]
 21%|██        | 621/3000 [00:50<03:11, 12.45it/s]
 21%|██        | 623/3000 [00:50<03:10, 12.45it/s]
 21%|██        | 625/3000 [00:50<03:11, 12.42it/s]
 21%|██        | 627/3000 [00:50<03:10, 12.43it/s]
 21%|██        | 629/3000 [00:51<03:10, 12.46it/s]
 21%|██        | 631/3000 [00:51<03:10, 12.47it/s]
 21%|██        | 633/3000 [00:51<03:09, 12.50it/s]
 21%|██        | 635/3000 [00:51<03:09, 12.50it/s]
 21%|██        | 637/3000 [00:51<03:09, 12.49it/s]
 21%|██▏       | 639/3000 [00:51<03:09, 12.46it/s]
 21%|██▏       | 641/3000 [00:52<03:09, 12.45it/s]
 21%|██▏       | 643/3000 [00:52<03:09, 12.42it/s]
 22%|██▏       | 645/3000 [00:52<03:09, 12.40it/s]
 22%|██▏       | 647/3000 [00:52<03:09, 12.39it/s]
 22%|██▏       | 649/3000 [00:52<03:09, 12.38it/s]
 22%|██▏       | 651/3000 [00:52<03:09, 12.39it/s]
 22%|██▏       | 653/3000 [00:52<03:09, 12.40it/s]
 22%|██▏       | 655/3000 [00:53<03:08, 12.42it/s]
 22%|██▏       | 657/3000 [00:53<03:07, 12.48it/s]
 22%|██▏       | 659/3000 [00:53<03:07, 12.50it/s]
 22%|██▏       | 661/3000 [00:53<03:07, 12.51it/s]
 22%|██▏       | 663/3000 [00:53<03:07, 12.47it/s]
 22%|██▏       | 665/3000 [00:53<03:07, 12.46it/s]
 22%|██▏       | 667/3000 [00:54<03:07, 12.45it/s]
 22%|██▏       | 669/3000 [00:54<03:07, 12.44it/s]
 22%|██▏       | 671/3000 [00:54<03:07, 12.43it/s]
 22%|██▏       | 673/3000 [00:54<03:07, 12.41it/s]
 22%|██▎       | 675/3000 [00:54<03:07, 12.41it/s]
 23%|██▎       | 677/3000 [00:54<03:07, 12.42it/s]
 23%|██▎       | 679/3000 [00:55<03:07, 12.37it/s]
 23%|██▎       | 681/3000 [00:55<03:08, 12.32it/s]
 23%|██▎       | 683/3000 [00:55<03:08, 12.29it/s]
 23%|██▎       | 685/3000 [00:55<03:08, 12.30it/s]
 23%|██▎       | 687/3000 [00:55<03:07, 12.33it/s]
 23%|██▎       | 689/3000 [00:55<03:07, 12.33it/s]
 23%|██▎       | 691/3000 [00:56<03:06, 12.37it/s]
 23%|██▎       | 693/3000 [00:56<03:06, 12.40it/s]
 23%|██▎       | 695/3000 [00:56<03:05, 12.42it/s]
 23%|██▎       | 697/3000 [00:56<03:05, 12.41it/s]
 23%|██▎       | 699/3000 [00:56<03:05, 12.40it/s]
 23%|██▎       | 701/3000 [00:56<03:05, 12.40it/s]
 23%|██▎       | 703/3000 [00:57<03:05, 12.38it/s]
 24%|██▎       | 705/3000 [00:57<03:05, 12.38it/s]
 24%|██▎       | 707/3000 [00:57<03:04, 12.41it/s]
 24%|██▎       | 709/3000 [00:57<03:04, 12.40it/s]
 24%|██▎       | 711/3000 [00:57<03:04, 12.39it/s]
 24%|██▍       | 713/3000 [00:57<03:04, 12.40it/s]
 24%|██▍       | 715/3000 [00:57<03:04, 12.38it/s]
 24%|██▍       | 717/3000 [00:58<03:04, 12.38it/s]
 24%|██▍       | 719/3000 [00:58<03:04, 12.40it/s]
 24%|██▍       | 721/3000 [00:58<03:04, 12.38it/s]
 24%|██▍       | 723/3000 [00:58<03:04, 12.37it/s]
 24%|██▍       | 725/3000 [00:58<03:04, 12.34it/s]
 24%|██▍       | 727/3000 [00:58<03:03, 12.35it/s]
 24%|██▍       | 729/3000 [00:59<03:03, 12.39it/s]
 24%|██▍       | 731/3000 [00:59<03:02, 12.41it/s]
 24%|██▍       | 733/3000 [00:59<03:02, 12.42it/s]
 24%|██▍       | 735/3000 [00:59<03:02, 12.41it/s]
 25%|██▍       | 737/3000 [00:59<03:02, 12.41it/s]
 25%|██▍       | 739/3000 [00:59<03:02, 12.41it/s]
 25%|██▍       | 741/3000 [01:00<03:02, 12.37it/s]
 25%|██▍       | 743/3000 [01:00<03:02, 12.36it/s]
 25%|██▍       | 745/3000 [01:00<03:02, 12.33it/s]
 25%|██▍       | 747/3000 [01:00<03:03, 12.30it/s]
 25%|██▍       | 749/3000 [01:00<03:03, 12.27it/s]
 25%|██▌       | 751/3000 [01:00<03:02, 12.29it/s]
 25%|██▌       | 753/3000 [01:01<03:01, 12.36it/s]
 25%|██▌       | 755/3000 [01:01<03:00, 12.41it/s]
 25%|██▌       | 757/3000 [01:01<03:00, 12.42it/s]
 25%|██▌       | 759/3000 [01:01<02:59, 12.47it/s]

0

In [16]:
import json
import re
import pandas as pd
from pathlib import Path
from IPython.display import display, Markdown

P1 = '/content/VCD_project/myTasks'
SEED = 55
out_dir = Path(f'{P1}/output')

def parse_metrics_txt(path: Path):
    if not path.exists(): return None
    text = path.read_text()
    def g(name):
        m = re.search(rf"^{name}:\s*([0-9.]+)", text, re.MULTILINE)
        return float(m.group(1)) if m else 0.0
    return {'Accuracy': g('Accuracy'), 'Precision': g('Precision'), 'Recall': g('Recall'), 'F1': g('F1')}

def parse_metrics_json(path: Path):
    if not path.exists(): return None
    data = json.loads(path.read_text())
    return {'Accuracy': float(data.get('accuracy', 0.0)), 
            'Precision': float(data.get('precision', 0.0)), 
            'Recall': float(data.get('recall', 0.0)), 
            'F1': float(data.get('f1_score') or data.get('f1') or 0.0) }

# --- Data Collection ---
rows = []
# Define the order we want to see them in the table
configs = [
    ('random', 'Regular', out_dir / f'metrics_random_regular_seed{SEED}.txt', parse_metrics_txt),
    ('random', 'VCD', out_dir / f'metrics_random_vcd_seed{SEED}.txt', parse_metrics_txt),
    ('random', 'MFCD', out_dir / 'mfcd_random.json', parse_metrics_json),
    ('popular', 'Regular', out_dir / f'metrics_popular_regular_seed{SEED}.txt', parse_metrics_txt),
    ('popular', 'VCD', out_dir / f'metrics_popular_vcd_seed{SEED}.txt', parse_metrics_txt),
    ('popular', 'MFCD', out_dir / 'mfcd_popular.json', parse_metrics_json),
]

for split, method, path, parser in configs:
    m = parser(path)
    if m: rows.append({'Split': split, 'Method': method, **m})

if rows:
    df = pd.DataFrame(rows)
    
    # Calculate Improvements relative to the previous row in the same split
    df['Gain vs Prev (%)'] = 0.0
    for split in df['Split'].unique():
        idx = df[df['Split'] == split].index
        for i in range(1, len(idx)):
            prev_f1 = df.loc[idx[i-1], 'F1']
            curr_f1 = df.loc[idx[i], 'F1']
            if prev_f1 > 0:
                df.at[idx[i], 'Gain vs Prev (%)'] = ((curr_f1 - prev_f1) / prev_f1) * 100

    # Styling for Jupyter
    def color_gain(val):
        color = 'green' if val > 0 else ('red' if val < 0 else 'gray')
        return f'color: {color}; font-weight: bold'

    styled_df = df.style.format({
        'Accuracy': '{:.4f}', 'Precision': '{:.4f}', 'Recall': '{:.4f}', 
        'F1': '{:.4f}', 'Gain vs Prev (%)': '{:+.2f}%'
    }).map(color_gain, subset=['Gain vs Prev (%)']).hide(axis='index')

    display(Markdown(f"### 📊 Full Benchmark: Regular vs VCD vs MFCD (Seed: {SEED})"))
    display(styled_df)
else:
    print("⚠️ No output files found. Check your /output directory.")

### 📊 Full Benchmark: Regular vs VCD vs MFCD (Seed: 55)